!********************************************************************************
!> @brief Flow variables and procedures.
!!
!! This module contains the variables and procedures used for the numerical
!! solution of the model, including source initialization, lobe generation,
!! flow emplacement, geometric utilities, and rasterization routines.
!!
!! Copyright: M. de' Michieli Vitturi, S. Tarquini
!! All copyright notices within source files and as generated by
!! the Software as output must be retained, unchanged.
!!
!! @date 2026-04-02
!! @author M. de' Michieli Vitturi
!! @author S. Tarquini
!********************************************************************************

MODULE flow

   USE parameters, ONLY : wp, eps

   IMPLICIT NONE

   !> number of lobes
   INTEGER :: alloc_n_lobes

   !> orientation angles of the lobes
   REAL(wp), ALLOCATABLE :: angle(:)

   !> x-coordinate of the center of the lobes
   REAL(wp), ALLOCATABLE :: x(:)

   !> x-coordinate of the center of the lobes
   REAL(wp), ALLOCATABLE :: y(:)

   !> first semi-axis of the lobes
   REAL(wp), ALLOCATABLE :: x1(:)

   !> first semi-axis of the lobes
   REAL(wp), ALLOCATABLE :: x2(:)

   !> thickness of the lobes
   REAL(wp), ALLOCATABLE :: h(:)

   !> distances (in lobes) from the vent
   INTEGER, ALLOCATABLE :: dist_int(:)

   !> number of descendents of the lobes
   INTEGER, ALLOCATABLE :: descendents(:)

   !> index of parent of the lobes
   INTEGER, ALLOCATABLE :: parent(:)

   !> Topography+flow elevation
   REAL(wp), ALLOCATABLE :: Ztot(:,:)

   !> Flow thickness
   REAL(wp), ALLOCATABLE :: Zflow(:,:)
   REAL(wp), ALLOCATABLE :: Zflow_mask(:,:)

   !> Flow thickness for uniondiff
   REAL(wp), ALLOCATABLE :: Zud(:,:)

   !> Map of lobe distances from the vent
   INTEGER, ALLOCATABLE :: Dist(:,:)

   !> Bounding-box north indexes of the lobes
   INTEGER, ALLOCATABLE :: jNorth_array(:)

   !> Bounding-box south indexes of the lobes
   INTEGER, ALLOCATABLE :: jSouth_array(:)

   !> Bounding-box east indexes of the lobes
   INTEGER, ALLOCATABLE :: iEast_array(:)

   !> Bounding-box west indexes of the lobes
   INTEGER, ALLOCATABLE :: iWest_array(:)

   !> Local map of flow thickness for each lobe
   REAL(wp), ALLOCATABLE :: Zflow_local_array(:,:,:)

   !> Cumulative probabilities of sources
   REAL(wp), ALLOCATABLE :: cum_source_prob(:)

   REAL(wp), ALLOCATABLE :: xv(:)
   REAL(wp), ALLOCATABLE :: yv(:)

   INTEGER :: max_cells
   REAL(wp) :: max_semiaxis

   INTEGER :: n_lobes_tot

   REAL(wp) :: inv_cell

   !> Cumulative erupted volume already emplaced before the current flow
   REAL(wp) :: Vcum_emplaced

CONTAINS

   !***********************************************************************
   !> @brief Allocate and initialize the main flow data structures.
   !!
   !! Allocates the arrays used to store lobe geometry, parent-child
   !! relationships, topography plus flow elevation, flow thickness, and
   !! local lobe masks. The subroutine also computes auxiliary quantities
   !! needed during the simulation, such as the maximum number of lobes to
   !! allocate, the meshgrid of local coordinates, the inverse cell size,
   !! the maximum semi-axis, and the maximum local stencil size.
   !!
   !! The number of lobes to allocate is determined either directly from
   !! `max_n_lobes` or from a beta-distribution-based scaling between
   !! `min_n_lobes` and `max_n_lobes`, depending on the values of
   !! `a_beta` and `b_beta`.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !!
   !! @note This subroutine has no explicit input or output arguments.
   !! It operates on module variables and parameters imported from
   !! `parameters`.
   !***********************************************************************
   SUBROUTINE allocate_flow

      USE parameters, ONLY : a_beta, b_beta, max_n_lobes, n_flows
      USE parameters, ONLY : min_n_lobes, max_n_lobes
      USE parameters, ONLY : nv, nv2, cell
      USE parameters, ONLY : lobe_area, max_aspect_ratio
      USE parameters, ONLY : nx, ny
      USE parameters, ONLY : union_diff_flag

      IMPLICIT NONE

      REAL(wp) :: beta_pdf(n_flows)
      REAL(wp) :: x_beta(n_flows)

      INTEGER :: i, j

      REAL(wp) :: xlin(nv), ylin(nv)

      ! Logic for determining alloc_n_lobes
      if (a_beta .LE. 0.0_wp .and. b_beta .LE. 0.0_wp) then

         alloc_n_lobes = max_n_lobes

      else

         ! This would be a manual calculation or a call to a Fortran beta distribution function.
         ! For simplicity, let's assume x_beta and beta_pdf have been calculated similarly as in Python.
         ! Here we should manually calculate the values, for now using placeholder values.

         ! Calculate x_beta (equivalent to np.rint(range(0, n_flows)) / (n_flows - 1))
         do i = 1, n_flows
            x_beta(i) = real(i - 1) / real(n_flows - 1)
         end do

         ! Calculate beta_pdf (you might need to implement or use a library for this)
         ! Assuming placeholder beta_pdf values for this translation
         beta_pdf = [0.1, 0.3, 0.5, 0.7, 0.9]

         alloc_n_lobes = int(min_n_lobes + 0.5 * (max_n_lobes - min_n_lobes) * maxval(beta_pdf))

         ! print *, 'Flow with the maximum number of lobes', maxloc(beta_pdf)

      end if

      ! print *, 'Maximum number of lobes', alloc_n_lobes

      ALLOCATE( angle(alloc_n_lobes) , x(alloc_n_lobes) , y(alloc_n_lobes) )
      ALLOCATE( x1(alloc_n_lobes) , x2(alloc_n_lobes) , h(alloc_n_lobes) )
      ALLOCATE( dist_int(alloc_n_lobes) , descendents(alloc_n_lobes) )
      ALLOCATE( parent(alloc_n_lobes) )

      ! Create linspace equivalent (linearly spaced values)
      do i = 1, nv
         xlin(i) = -0.5 * cell + (i - 1) * cell / (nv - 1)
         ylin(i) = -0.5 * cell + (i - 1) * cell / (nv - 1)
      end do

      ! Calculate the total number of grid points in the meshgrid
      nv2 = nv * nv

      ALLOCATE( xv(nv2) )
      ALLOCATE( yv(nv2) )

      ! Create meshgrid equivalent
      do j = 1, nv
         do i = 1, nv
            xv((j-1)*nv + i) = xlin(i)
            yv((j-1)*nv + i) = ylin(j)
         end do
      end do

      ! Calculate the maximum semi-axis (equivalent to max_semiaxis in Python)
      max_semiaxis = sqrt(lobe_area * max_aspect_ratio / 3.141592653589793)

      inv_cell = 1.0_wp / cell

      ! Calculate the maximum number of cells (equivalent to max_cells in Python)
      max_cells = int(ceiling(2.0 * max_semiaxis * inv_cell)) + 2

      ! Print the result (optional)
      ! print *, 'Max Cells:', max_cells

      ALLOCATE( jNorth_array(alloc_n_lobes) )
      ALLOCATE( jSouth_array(alloc_n_lobes) )
      ALLOCATE( iEast_array(alloc_n_lobes) )
      ALLOCATE( iWest_array(alloc_n_lobes) )

      ALLOCATE( Ztot(ny,nx) ,  Zflow(ny,nx) ,  Zflow_mask(ny,nx) )
      ALLOCATE( Zflow_local_array(alloc_n_lobes,max_cells,max_cells) )

      IF (union_diff_flag) ALLOCATE( Zud(ny,nx) )

      RETURN


   END SUBROUTINE allocate_flow


   !***********************************************************************
   !> @brief Control the main emplacement loop for all flows and lobes.
   !!
   !! Manages the full simulation workflow for lava emplacement by looping
   !! over all flows and, within each flow, over the corresponding lobes.
   !! For each new flow, the initial lobe is generated and the subsequent
   !! lobes are added according to the model parameters controlling lobe
   !! growth, branching, topographic interaction, and stopping conditions.
   !!
   !! During execution, the subroutine updates the flow thickness field,
   !! the topography modified by emplacement, and the counters tracking
   !! the number of generated flows and lobes. It also handles intermediate
   !! and final output writing when requested by the input settings.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !!
   !! @note This subroutine has no explicit input or output arguments.
   !! It operates on module variables and parameters imported from
   !! `parameters`.
   !***********************************************************************
   SUBROUTINE flow_loop

      USE parameters, ONLY : nx,ny
      USE parameters, ONLY : xcmin, ycmin
      USE parameters, ONLY : nd
      USE parameters, ONLY : Ztopo
      USE parameters, ONLY : filling_parameter
      USE parameters, ONLY : n_flows, n_init
      USE parameters, ONLY : a_beta, b_beta
      USE parameters, ONLY : min_n_lobes, max_n_lobes
      USE parameters, ONLY : thickness_ratio, avg_lobe_thickness
      USE parameters, ONLY : lobe_exponent
      USE parameters, ONLY : lobe_area

      IMPLICIT NONE

      INTEGER :: last_lobe

      INTEGER :: i_flow
      INTEGER :: i
      REAL(wp) :: random_value
      INTEGER :: n_lobes
      REAL(wp) :: thickness_min
      REAL(wp) :: delta_lobe_thickness

      REAL(wp) :: max_slope_angle, slope

      INTEGER :: i_West, i_East, j_South, j_North
      INTEGER :: nx_local, ny_local
      REAL(wp) :: Zflow_local(max_cells,max_cells)
      integer :: Dist_local(max_cells,max_cells)
      INTEGER :: Zflow_local_int(max_cells,max_cells)

      REAL(wp) :: lobe_thickness

      INTEGER :: idx

      INTEGER :: ix, ix1
      INTEGER :: iy, iy1
      REAL(wp) :: xi, yi

      REAL(wp) :: zidx
      REAL(wp) :: temp_angle

      REAL(wp) :: cos_angle1, sin_angle1
      REAL(wp) :: new_angle

      LOGICAL :: check_step

      Ztot(1:ny,1:nx) = Ztopo(1:ny,1:nx)
      Zflow(1:ny,1:nx) = 0.0_wp
      n_lobes_tot = 0
      Vcum_emplaced = 0.0_wp

      WRITE(*,*) 'Computing flow'
      call random_seed()  ! Initialize the random number generator

      DO i_flow = 1,n_flows

         IF (n_flows>1) THEN

            WRITE(*,FMT="(A1,A,t21,F6.2,A)",ADVANCE="NO") ACHAR(13),              &
            & " Percent Complete: " ,                                        &
               ( REAL(i_flow) / REAL(n_flows))*100.0, "%"

         END IF

         Zflow_local_array = 0.0_wp

         if (a_beta .LE. 0.0_wp .AND. b_beta .LE. 0.0_wp) then


            ! Generate a random value uniformly distributed between min_n_lobes
            ! and max_n_lobes
            call random_number(random_value)
            random_value = 0.5_wp
            random_value = min_n_lobes + (max_n_lobes-min_n_lobes) * random_value

            ! Calculate n_lobes by rounding up and converting to integer
            n_lobes = int(ceiling(random_value))

         ELSE

            ! TO DO
            n_lobes = min_n_lobes

         END if

         ! Print the result (optional)
         ! print *, 'Number of lobes:', n_lobes

         n_lobes_tot = n_lobes_tot + n_lobes

         ! Calculate thickness_min
         thickness_min = 2.0_wp * thickness_ratio /                               &
            (thickness_ratio + 1.0_wp) * avg_lobe_thickness

         ! Calculate delta_lobe_thickness
         delta_lobe_thickness = 2.0_wp * &
            (avg_lobe_thickness - thickness_min) / (n_lobes - 1.0_wp)

         ! Print the results (optional)
         ! print *, 'Minimum Lobe Thickness:', thickness_min
         ! print *, 'Delta Lobe Thickness:', delta_lobe_thickness

         DO i = 1,n_init

            IF (n_flows==1) THEN

               WRITE(*,FMT="(A1,A,t21,F6.2,A)",ADVANCE="NO") ACHAR(13),              &
               & " Percent Complete: " ,                                        &
                  ( REAL(i) / REAL(n_lobes))*100.0, "%"

            END IF

            CALL first_lobe(i_flow, x(i), y(i))

            dist_int(i) = 0
            descendents(i) = 0

            CALL step1A(x(i), y(i), max_slope_angle, slope)

            CALL step2(slope, max_slope_angle, angle(i))

            CALL compute_semiaxis(slope,x1(i), x2(i))

            CALL rasterize(x(i), y(i), x1(i), x2(i), angle(i), dist_int(i),       &
               i_West, i_East, j_South, j_North, Zflow_local, Dist_local,       &
               Zflow_local_int)

            ! compute the thickness of the lobe
            lobe_thickness = thickness_min + (i - 1) * delta_lobe_thickness

            nx_local = i_East - i_West
            ny_local = j_North - j_South

            ! update the thickness of the flow with the new lobe
            Zflow(j_South:j_North-1, i_West:i_East-1) =                               &
               Zflow(j_South:j_North-1, i_West:i_East-1)                            &
               + lobe_thickness * Zflow_local(1:ny_local,1:nx_local)

            ! update the topography
            Ztot(j_South:j_North-1, i_West:i_East-1) =                                &
               Ztot(j_South:j_North-1, i_West:i_East-1)                             &
               + filling_parameter(j_South:j_North-1, i_West:i_East-1)              &
               * lobe_thickness * Zflow_local(1:ny_local,1:nx_local)

            ! Update the cumulative erupted volume with the new deposited lobe
            Vcum_emplaced = Vcum_emplaced + lobe_thickness * lobe_area

            ! store the bounding box of the new lobe
            jNorth_array(i) = j_North
            jSouth_array(i) = j_South

            iEast_array(i) = i_East
            iWest_array(i) = i_West

         END DO

         last_lobe = n_lobes

         DO i = n_init+1,n_lobes

            IF (n_flows==1) THEN

               WRITE(*,FMT="(A1,A,t21,F6.2,A)",ADVANCE="NO") ACHAR(13),              &
               & " Percent Complete: " ,                                        &
                  ( REAL(i) / REAL(n_lobes))*100.0, "%"

            END IF

            IF ( (lobe_exponent - 0.0_wp) > eps ) THEN

               CALL step0(i, dist_int(1:i), idx)

            ELSE

               idx = i - 1

            END IF

            ! save the index of the parent and the distance from first lobe of the
            ! chain
            parent(i) = idx
            dist_int(i) = dist_int(idx) + 1

            ! ix,iy are the indexes of the grid cell of the lobe center
            CALL coorToIdx(x(idx), xcmin, inv_cell, ix, xi)
            CALL coorToIdx(y(idx), ycmin, inv_cell, iy, yi)

            ix1 = ix + 1
            iy1 = iy + 1

            ! stopping condition (lobe close the domain boundary)
            IF ( (ix <= 0.5 * max_cells) .OR. (ix1 >= (nx - 0.5*max_cells)) .OR.  &
               (iy <= 0.5 * max_cells) .OR. (iy1 >= (ny - 0.5*max_cells)) .OR.  &
               (abs(Ztopo(iy, ix)-nd)<=eps) .OR. (abs(Ztopo(iy1, ix1)-nd)<=eps) .OR.          &
               (abs(Ztopo(iy, ix1)-nd)<=eps) .OR. (ABS(Ztopo(iy1, ix)-nd)<=eps) ) THEN

               WRITE(*,*) 'ERROR : the lava has reached the DEM margin'
               IF (ix <= 0.5 * max_cells) WRITE(*,*) 'Please increase west_to_vent'
               IF (ix1 >= (nx - 0.5*max_cells)) WRITE(*,*) 'Please increase east_to_vent'
               IF (iy <= 0.5 * max_cells) WRITE(*,*) 'Please increase south_to_vent'
               IF (iy1 >= (ny - 0.5*max_cells)) WRITE(*,*) 'Please increase north_to_vent'

               last_lobe = i - 1

               EXIT

            END IF

            CALL step1(xi, ix, yi, iy, x(idx), y(idx), x1(idx), x2(idx),          &
               angle(idx), slope, max_slope_angle, zidx)

            CALL step2(slope, max_slope_angle, temp_angle)

            CALL step3(angle(idx),  temp_angle, slope, cos_angle1, sin_angle1,    &
               new_angle)

            CALL step4and5(new_angle, angle(idx), x1(idx), x2(idx), x(idx),       &
               y(idx), zidx, cos_angle1, sin_angle1, check_step, x(i), y(i),    &
               x1(i), x2(i), angle(i))

            IF (.NOT.check_step) THEN

               last_lobe = i-1
               EXIT

            END IF

            CALL rasterize(x(i), y(i), x1(i), x2(i), angle(i), dist_int(i),       &
               i_West, i_East, j_South, j_North, Zflow_local, Dist_local,       &
               Zflow_local_int)

            nx_local = i_East - i_West
            ny_local = j_North - j_South

            ! compute the thickness of the lobe
            lobe_thickness = thickness_min + (i - 1) * delta_lobe_thickness

            ! update the thickness of the flow with the new lobe
            Zflow(j_South:j_North-1, i_West:i_East-1) =                           &
               Zflow(j_South:j_North-1, i_West:i_East-1)                        &
               + lobe_thickness * Zflow_local(1:ny_local,1:nx_local)

            ! update the topography
            Ztot(j_South:j_North-1, i_West:i_East-1) =                            &
               Ztot(j_South:j_North-1, i_West:i_East-1)                         &
               + filling_parameter(j_South:j_North-1, i_West:i_East-1)          &
               * lobe_thickness * Zflow_local(1:ny_local,1:nx_local)

            ! Update the cumulative erupted volume with the new deposited lobe
            Vcum_emplaced = Vcum_emplaced + lobe_thickness * lobe_area

            ! store the bounding box of the new lobe
            jNorth_array(i) = j_North
            jSouth_array(i) = j_South

            iEast_array(i) = i_East
            iWest_array(i) = i_West

         END DO

      END DO

      WRITE(*,'(A)') ' '
      WRITE(*,'(A,ES18.10)') ' Final cumulative deposited volume = ', Vcum_emplaced

      RETURN

   END SUBROUTINE flow_loop

   !***********************************************************************
   !> @brief Initialize the internal source representation.
   !!
   !! Builds the internal source arrays used by the flow module starting
   !! from the vent geometry specified in the input parameters.
   !! Depending on the value of `vent_flag`, point vents are converted into
   !! degenerate line sources, polyline vents are split into consecutive
   !! segments, and independent fissures are copied directly into the
   !! internal source representation. For unsupported or inactive source
   !! configurations, the internal source arrays are initialized to zero.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !!
   !! @note This subroutine has no explicit input or output arguments.
   !! It operates on module variables imported from `parameters`.
   !***********************************************************************
   subroutine init_sources

      USE parameters, ONLY : n_sources
      USE parameters, ONLY : vent_flag
      USE parameters, ONLY : x_vent, y_vent
      USE parameters, ONLY : x_vent_end, y_vent_end
      USE parameters, ONLY : x_source, y_source
      USE parameters, ONLY : x_source_end, y_source_end

      implicit none

      INTEGER :: j

      !> Allocate the internal line-source arrays
      if (allocated(x_source)) deallocate(x_source, y_source, x_source_end, &
         y_source_end)

      allocate(x_source(n_sources), y_source(n_sources), &
         x_source_end(n_sources), y_source_end(n_sources))

      !> Initialize the internal line sources according to the current
      !> vent geometry
      SELECT CASE ( vent_flag )

       CASE ( 0 , 1 , 8 )

         !> Point sources are mapped into the internal source
         !> representation by assigning identical start and end points
         do j = 1, n_sources

            x_source(j) = x_vent(j)
            y_source(j) = y_vent(j)

            x_source_end(j) = x_vent(j)
            y_source_end(j) = y_vent(j)

         end do

       CASE ( 2 , 3 , 6 )

         !> A polyline defined by n_vents points is converted into
         !> n_sources = n_vents-1 line sources
         do j = 1, n_sources

            x_source(j) = x_vent(j)
            y_source(j) = y_vent(j)

            x_source_end(j) = x_vent(j+1)
            y_source_end(j) = y_vent(j+1)

         end do

       CASE ( 4 , 5 , 7 )

         !> Independent fissures are copied directly into the internal
         !> line-source representation
         do j = 1, n_sources

            x_source(j) = x_vent(j)
            y_source(j) = y_vent(j)

            x_source_end(j) = x_vent_end(j)
            y_source_end(j) = y_vent_end(j)

         end do

       CASE DEFAULT

         !> Default initialization for vent flags that do not use line
         !> sources
         x_source(:) = 0.0_wp
         y_source(:) = 0.0_wp
         x_source_end(:) = 0.0_wp
         y_source_end(:) = 0.0_wp

      END SELECT

   end subroutine init_sources

   !***********************************************************************
   !> @brief Build the cumulative probability distribution for source selection.
   !!
   !! Computes and allocates the cumulative probability array used to select
   !! an eruptive source according to the current source geometry and
   !! `vent_flag` configuration.
   !!
   !! For `vent_flag = 2` and `4`, source probabilities are proportional to
   !! source length. For `vent_flag = 3` and `5`, sources are assigned
   !! uniform probability. For `vent_flag = 7` and `8`, probabilities are
   !! taken from the user-defined array `source_probabilities`. For all
   !! other cases, the cumulative probability array is initialized to zero
   !! because cumulative probabilistic source selection is not used.
   !!
   !! If only one source is available, the cumulative probability is set
   !! directly to 1.0. The subroutine also checks that the resulting
   !! cumulative distribution is monotonic and terminates with an error
   !! message if invalid user-defined probabilities are provided or if the
   !! cumulative distribution is inconsistent.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !!
   !! @note This subroutine has no explicit input or output arguments.
   !! It operates on module variables and parameters imported from
   !! `parameters`.
   !***********************************************************************
   subroutine build_source_cdf

      USE parameters, ONLY : n_sources
      USE parameters, ONLY : source_probabilities, vent_flag
      USE parameters, ONLY : x_source, y_source
      USE parameters, ONLY : x_source_end, y_source_end

      implicit none

      ! Local variables
      REAL(wp) :: delta_x, delta_y

      REAL(wp) :: tot_prob

      INTEGER :: j


      if (allocated(cum_source_prob)) deallocate(cum_source_prob)
      allocate(cum_source_prob(n_sources))

      cum_source_prob = 0.0_wp

      IF ( n_sources == 1 ) THEN
         cum_source_prob(1) = 1.0_wp
         RETURN
      END IF

      !> Build the cumulative probabilities associated with the discrete
      !> sources for the current vent geometry and selection mode
      SELECT CASE ( vent_flag )

       CASE ( 2 , 4 )

         !> vent_flag = 2: polyline segments selected with probability
         !> proportional to their length
         !> vent_flag = 4: independent fissures selected with probability
         !> proportional to their length

         tot_prob = 0.0_wp

         do j = 1, n_sources

            delta_x = x_source_end(j) - x_source(j)
            delta_y = y_source_end(j) - y_source(j)

            tot_prob = tot_prob + sqrt( delta_x**2 + delta_y**2 )
            cum_source_prob(j) = tot_prob

         end do

         cum_source_prob(1:n_sources) = cum_source_prob(1:n_sources) / &
            cum_source_prob(n_sources)

       CASE ( 3 , 5 )

         !> vent_flag = 3: polyline segments selected with uniform
         !> probability
         !> vent_flag = 5: independent fissures selected with uniform
         !> probability

         do j = 1, n_sources
            cum_source_prob(j) = REAL(j,wp) / REAL(n_sources,wp)
         end do

       CASE ( 6 , 7 , 8 )

         !> vent_flag = 6,7,8: sources selected according to user-defined
         !> probabilities
         IF ( allocated(source_probabilities) .AND. &
            ABS(source_probabilities(1) - (-9999.0_wp)) >= eps ) THEN

            cum_source_prob(1:n_sources) = &
               cumsum( source_probabilities(1:n_sources) )

            cum_source_prob(1:n_sources) = cum_source_prob(1:n_sources) / &
               cum_source_prob(n_sources)

         ELSE

            WRITE(*,*)
            WRITE(*,*) 'ERROR: source_probabilities not properly defined'
            WRITE(*,*) 'for probabilistic vent selection'
            WRITE(*,*)
            STOP

         END IF

       CASE DEFAULT

         !> Default initialization for vent flags that do not use
         !> cumulative source probabilities
         cum_source_prob(1:n_sources) = 0.0_wp

      END SELECT

      cum_source_prob(n_sources) = 1.0_wp

      IF ( ANY( cum_source_prob(2:n_sources) < cum_source_prob(1:n_sources-1) ) ) THEN
         WRITE(*,*) 'ERROR: cum_source_prob is not monotonic'
         STOP
      END IF

      RETURN

   end subroutine build_source_cdf

   !***********************************************************************
   !> @brief Compute the cumulative sum of a one-dimensional real array.
   !!
   !! Returns an array whose elements contain the cumulative sum of the
   !! input array elements from the first position up to the current one.
   !! The output has the same size as the input array and is used to build
   !! cumulative distributions or progressive totals required by the model.
   !!
   !! @param[in] arr Input one-dimensional real array.
   !! @return cumsum_array One-dimensional real array containing the
   !! cumulative sum of `arr`.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   pure function cumsum(a) result (r)
      real(wp), intent(in) :: a(:)
      real(wp) :: r(size(a))
      integer :: i
      r(:) = [(sum(a(1:i)),i=1,size(a))]
   end function cumsum

   !***********************************************************************
   !> @brief Generate and initialize the first lobe of a new flow.
   !!
   !! Selects the eruptive source for the current flow according to the
   !! active source-selection mode and computes the coordinates of the
   !! initial emplacement point of the new flow.
   !!
   !! The source can be chosen deterministically, uniformly, or through a
   !! weighted cumulative distribution, depending on the value of
   !! `vent_flag`. The subroutine also evaluates the cumulative erupted
   !! volume already emplaced in the domain and activates only the sources
   !! whose activation window satisfies
   !! `source_volume_from(i) <= Vcum < source_volume_to(i)`.
   !! If more than one source is active, the selection rule is applied only
   !! to the active subset. If no source is active, the simulation stops
   !! with an error message.
   !!
   !! For point sources, the selected coordinates are used directly. For
   !! line sources or fissures, a point is sampled uniformly along the
   !! selected segment.
   !!
   !! @param[in]  i_flow Index of the current flow.
   !! @param[out] x_i    X coordinate of the first lobe emplacement point.
   !! @param[out] y_i    Y coordinate of the first lobe emplacement point.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine first_lobe(i_flow, x_i, y_i)

      USE parameters, ONLY : n_sources
      USE parameters, ONLY : x_source, y_source
      USE parameters, ONLY : x_source_end, y_source_end
      USE parameters, ONLY : vent_flag
      USE parameters, ONLY : n_flows
      USE parameters, ONLY : source_volume_from, source_volume_to
      USE parameters, ONLY : source_probabilities

      implicit none

      ! Input
      INTEGER, INTENT(IN) :: i_flow

      ! Outputs
      real(wp), intent(out) :: x_i, y_i

      ! Local variables
      integer :: i, i_source
      real(wp) :: rand_val
      real(wp) :: alfa_source

      ! Active source flags and temporary weights for source selection
      LOGICAL, ALLOCATABLE :: source_is_active(:)
      REAL(wp), ALLOCATABLE :: active_source_weight(:)
      REAL(wp) :: Vcum

      ! Cumulative erupted volume already emplaced before the current flow
      Vcum = Vcum_emplaced

      ! Identify which sources are active at the current cumulative erupted volume
      ALLOCATE(source_is_active(n_sources))
      source_is_active = ( source_volume_from <= Vcum ) .AND. &
         ( Vcum < source_volume_to )

      ! Stop if no source is active at the current cumulative erupted volume
      IF ( .NOT. ANY(source_is_active) ) THEN
         WRITE(*,*) 'ERROR: no active source found for current cumulative erupted volume'
         WRITE(*,*) 'Vcum = ', Vcum
         STOP
      END IF

      ! Special case: only one source exists and it is active
      if ( n_sources == 1 ) then

         SELECT CASE ( vent_flag )

          CASE ( 2 , 3 , 4 , 5 , 6 , 7 )
            call random_number(alfa_source)

            x_i = x_source(1) + alfa_source * &
               ( x_source_end(1) - x_source(1) )

            y_i = y_source(1) + alfa_source * &
               ( y_source_end(1) - y_source(1) )

          CASE DEFAULT
            x_i = x_source(1)
            y_i = y_source(1)

         END SELECT

         DEALLOCATE(source_is_active)
         RETURN

      end if

      ! Allocate and initialize temporary source weights on the active subset
      ALLOCATE(active_source_weight(n_sources))
      active_source_weight = 0.0_wp

      ! Build temporary selection weights restricted to the active sources
      SELECT CASE ( vent_flag )

       CASE ( 0 , 1 , 3 , 5 )
         WHERE ( source_is_active )
            active_source_weight = 1.0_wp
         END WHERE

       CASE ( 2 , 4 )
         active_source_weight(1) = cum_source_prob(1)
         active_source_weight(2:n_sources) = cum_source_prob(2:n_sources) - &
            cum_source_prob(1:n_sources-1)

         WHERE ( .NOT. source_is_active )
            active_source_weight = 0.0_wp
         END WHERE

       CASE ( 7 , 8 )
         WHERE ( source_is_active )
            active_source_weight = source_probabilities
         END WHERE

       CASE DEFAULT
         CONTINUE

      END SELECT

      ! Check that the active sources have a positive total selection weight
      IF ( SUM(active_source_weight) <= 0.0_wp ) THEN
         WRITE(*,*) 'ERROR: active sources have zero total selection weight'
         WRITE(*,*) 'Vcum = ', Vcum
         STOP
      END IF

      ! Choose the initial lobe location based on the vent_flag value
      select case (vent_flag)

       case (0)

         ! vent_flag = 0: deterministic source assignment among active sources
         i_source = int(floor(real(i_flow-1,wp) * SUM(active_source_weight) / &
            real(n_flows,wp))) + 1

         do i = 1 , n_sources
            if ( source_is_active(i) ) then
               i_source = i_source - 1
               if ( i_source == 0 ) then
                  i_source = i
                  exit
               end if
            end if
         end do

         x_i = x_source(i_source)
         y_i = y_source(i_source)

       case (1)
         ! vent_flag = 1: initial lobes are chosen randomly
         ! among the active point sources with uniform probability
         call random_number(rand_val)

         alfa_source = rand_val * SUM(active_source_weight)

         i_source = 1
         do while ( ( i_source < n_sources ) .AND. &
            ( alfa_source > SUM(active_source_weight(1:i_source)) ) )
            i_source = i_source + 1
         end do

         x_i = x_source(i_source)
         y_i = y_source(i_source)

       case (2 , 4 , 7)
         ! vent_flag = 2: active polyline segments are selected
         ! with length-based probability
         ! vent_flag = 4: active fissures are selected
         ! with length-based probability
         ! vent_flag = 7: active fissures are selected
         ! with user-defined probabilities
         call random_number(rand_val)

         alfa_source = rand_val * SUM(active_source_weight)

         i_source = 1
         do while ( ( i_source < n_sources ) .AND. &
            ( alfa_source > SUM(active_source_weight(1:i_source)) ) )
            i_source = i_source + 1
         end do

         call random_number(alfa_source)

         x_i = x_source(i_source) + alfa_source * &
            ( x_source_end(i_source) - x_source(i_source) )

         y_i = y_source(i_source) + alfa_source * &
            ( y_source_end(i_source) - y_source(i_source) )

       case (3 , 5)
         ! vent_flag = 3: active polyline segments are chosen randomly
         ! with uniform probability
         ! vent_flag = 5: active fissures are chosen randomly
         ! with uniform probability
         call random_number(rand_val)

         alfa_source = rand_val * SUM(active_source_weight)

         i_source = 1
         do while ( ( i_source < n_sources ) .AND. &
            ( alfa_source > SUM(active_source_weight(1:i_source)) ) )
            i_source = i_source + 1
         end do

         call random_number(alfa_source)

         x_i = alfa_source * x_source_end(i_source) + &
            (1.0_wp - alfa_source) * x_source(i_source)

         y_i = alfa_source * y_source_end(i_source) + &
            (1.0_wp - alfa_source) * y_source(i_source)

       case (8)
         ! vent_flag = 8: active point vents are selected
         ! with user-defined probabilities
         call random_number(rand_val)

         alfa_source = rand_val * SUM(active_source_weight)

         i_source = 1
         do while ( ( i_source < n_sources ) .AND. &
            ( alfa_source > SUM(active_source_weight(1:i_source)) ) )
            i_source = i_source + 1
         end do

         x_i = x_source(i_source)
         y_i = y_source(i_source)

      end select



      ! Release temporary arrays used for active-source selection
      DEALLOCATE(source_is_active)
      DEALLOCATE(active_source_weight)

      RETURN

   end subroutine first_lobe

   !***********************************************************************
   !> @brief Compute the local maximum slope direction and slope magnitude.
   !!
   !! Evaluates the topographic gradient at the input point `(x_i, y_i)`
   !! by interpolating the elevation field `Ztot` within the grid cell
   !! containing the point. The interpolated gradient components are used
   !! to compute both the azimuth of the maximum downslope direction and
   !! the corresponding slope magnitude at the lobe center.
   !!
   !! The slope direction is returned in degrees in the range
   !! `[0, 360)`, while the slope magnitude is computed from the
   !! interpolated horizontal gradient components.
   !!
   !! @param[in]  x_i              X coordinate of the point where the local
   !!                              slope is evaluated.
   !! @param[in]  y_i              Y coordinate of the point where the local
   !!                              slope is evaluated.
   !! @param[out] max_slope_angle  Azimuth of the maximum slope direction,
   !!                              in degrees.
   !! @param[out] slope            Magnitude of the local topographic slope.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step1A(x_i, y_i, max_slope_angle, slope)

      USE parameters, ONLY : xcmin, ycmin

      implicit none

      ! Inputs
      real(wp), intent(in) :: x_i, y_i

      ! Outputs
      real(wp), intent(out) :: max_slope_angle, slope

      ! Local variables
      integer :: ix, iy, ix1, iy1
      real(wp) :: xi, yi, xi_fract, yi_fract
      real(wp) :: Fx_test, Fy_test

      ! Convert coordinates to grid indices
      call coorToIdx(x_i, xcmin, inv_cell, ix, xi)
      call coorToIdx(y_i, ycmin, inv_cell, iy, yi)

      ! Calculate baricentric coordinates (fraction within the cell)
      xi_fract = xi - real(ix) + 1.0_wp
      yi_fract = yi - real(iy) + 1.0_wp

      ix1 = ix+1
      iy1 = iy+1

      ! Interpolate slopes at the edges of the pixel
      Fx_test = (yi_fract * (Ztot(iy1, ix1) - Ztot(iy1, ix)) +                    &
         (1.0_wp - yi_fract) * (Ztot(iy, ix1) - Ztot(iy, ix))) * inv_cell

      Fy_test = (xi_fract * (Ztot(iy1, ix1) - Ztot(iy, ix1)) +                    &
         (1.0_wp - xi_fract) * (Ztot(iy1, ix) - Ztot(iy, ix))) * inv_cell

      ! Calculate the maximum slope angle (in degrees)
      max_slope_angle = mod(180.0_wp + atan2d(Fy_test, Fx_test), 360.0_wp)

      ! Calculate the slope at the lobe center
      slope = sqrt(Fx_test**2 + Fy_test**2)

      RETURN

   end subroutine step1A

   !***********************************************************************
   !> @brief Compute the semi-axes of a new elliptical lobe from the local slope.
   !!
   !! Computes the major and minor semi-axes of a lobe assuming an
   !! elliptical shape with prescribed area `lobe_area`. The aspect ratio
   !! is derived from the local slope and is limited by
   !! `max_aspect_ratio`.
   !!
   !! The square root of the aspect ratio is evaluated as
   !! `sqrt(min(max_aspect_ratio, 1.0_wp + aspect_ratio_coeff * slope))`.
   !! The two semi-axes are then computed so that the final ellipse
   !! preserves the target lobe area.
   !!
   !! @param[in]  slope   Local topographic slope used to determine the
   !!                     lobe aspect ratio.
   !! @param[out] new_x1  Semi-axis of the lobe along the major direction.
   !! @param[out] new_x2  Semi-axis of the lobe along the minor direction.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine compute_semiaxis(slope,new_x1, new_x2)

      USE parameters, ONLY : pi
      USE parameters, ONLY : lobe_area
      USE parameters, ONLY : max_aspect_ratio, aspect_ratio_coeff


      implicit none

      ! Inputs
      real(wp), intent(in) :: slope

      ! Outputs
      real(wp), intent(out) :: new_x1, new_x2

      ! Local variables
      real(wp) :: sqrt_aspect_ratio

      REAL(wp) :: num

      ! Compute the square root of aspect ratio
      sqrt_aspect_ratio = sqrt(min(max_aspect_ratio, 1.0_wp + aspect_ratio_coeff * slope))

      ! Compute the semi-axes of the elliptical lobe
      num = sqrt(lobe_area / pi)
      new_x1 = num * sqrt_aspect_ratio
      new_x2 = num / sqrt_aspect_ratio

      RETURN

   end subroutine compute_semiaxis

   !***********************************************************************
   !> @brief Convert a physical coordinate into a grid index and normalized coordinate.
   !!
   !! Transforms a physical coordinate into its corresponding normalized
   !! grid coordinate using the minimum domain value and the inverse grid
   !! spacing. The subroutine also computes the index of the grid cell
   !! containing the point.
   !!
   !! The normalized coordinate is evaluated as
   !! `coor_norm = (coor - minval) * inv_step`,
   !! while the cell index is computed as
   !! `idx = floor(coor_norm) + 1`.
   !!
   !! @param[in]  coor       Physical coordinate to be converted.
   !! @param[in]  minval     Minimum domain coordinate used as reference.
   !! @param[in]  inv_step   Inverse of the grid spacing along the
   !!                        corresponding direction.
   !! @param[out] idx        Index of the grid cell containing `coor`.
   !! @param[out] coor_norm  Normalized coordinate in grid units.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine coorToIdx(coor, minval, inv_step, idx, coor_norm)
      implicit none

      ! Inputs
      real(wp), intent(in) :: coor, minval, inv_step

      ! Outputs
      integer, intent(out) :: idx
      real(wp), intent(out) :: coor_norm

      ! Calculate the normalized coordinate
      coor_norm = (coor - minval) * inv_step

      ! Calculate the index of the cell containing the point
      idx = floor(coor_norm)+1

      RETURN

   end subroutine coorToIdx

   !***********************************************************************
   !> @brief Compute the grid-aligned bounding box of an ellipse.
   !!
   !! Determines the index range of the computational grid that encloses
   !! an ellipse described by its discretized boundary coordinates
   !! `xe` and `ye`.
   !!
   !! The subroutine first finds the minimum and maximum x and y values of
   !! the ellipse boundary, then converts these physical coordinates into
   !! grid indices using `coorToIdx`. The resulting indices are clipped to
   !! the valid grid domain limits. On the eastern and northern sides, the
   !! returned bounds are extended by two cells to ensure safe inclusion of
   !! the full ellipse footprint in subsequent local computations.
   !!
   !! @param[in]  xe       Array of x coordinates of the ellipse boundary.
   !! @param[in]  ye       Array of y coordinates of the ellipse boundary.
   !! @param[out] i_West   Western grid index of the bounding box.
   !! @param[out] i_East   Eastern grid index of the bounding box.
   !! @param[out] j_South  Southern grid index of the bounding box.
   !! @param[out] j_North  Northern grid index of the bounding box.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine bounding_box(xe, ye, i_West, i_East, j_South, j_North)

      USE parameters, ONLY : nx, ny
      USE parameters, ONLY : xcmin, ycmin

      implicit none

      ! Inputs
      real(wp), dimension(:), intent(in) :: xe, ye

      ! Outputs
      integer, intent(out) :: i_West, i_East, j_South, j_North

      ! Local variables
      real(wp) :: min_xe, max_xe, min_ye, max_ye
      real(wp) :: xi, yi
      integer :: idx_west, idx_east, idx_south, idx_north

      ! Find minimum and maximum x and y coordinates of the ellipse
      min_xe = minval(xe)
      max_xe = maxval(xe)
      min_ye = minval(ye)
      max_ye = maxval(ye)

      ! Compute the bounding box indices for the grid
      call coorToIdx(min_xe, xcmin, inv_cell, idx_west, xi)
      i_West = max(1, min(nx, idx_west))

      call coorToIdx(max_xe, xcmin, inv_cell, idx_east, xi)
      i_East = max(1, min(nx, idx_east+2))

      call coorToIdx(min_ye, ycmin, inv_cell, idx_south, yi)
      j_South = max(1, min(ny, idx_south))

      call coorToIdx(max_ye, ycmin, inv_cell, idx_north, yi)
      j_North = max(1, min(ny, idx_north+2 ))

      RETURN

   end subroutine bounding_box

   !***********************************************************************
   !> @brief Compute the discretized boundary of a rotated ellipse.
   !!
   !! Generates the coordinates of the points defining an ellipse centered
   !! at `(xc, yc)`, with semi-axes `ax1` and `ax2`, rotated by `angle`
   !! degrees.
   !!
   !! The ellipse is built starting from the reference unit-circle
   !! coordinates stored in `X_circle` and `Y_circle`, scaled by the two
   !! semi-axes and then rotated using the specified angle. The resulting
   !! coordinates are returned in the arrays `xe` and `ye`, which contain
   !! the discretized boundary points of the ellipse.
   !!
   !! Compared with the previous implementation, this version avoids the
   !! temporary arrays used for the scaled coordinates and computes the
   !! rotated ellipse coordinates directly.
   !!
   !! @param[in]  xc     X coordinate of the ellipse center.
   !! @param[in]  yc     Y coordinate of the ellipse center.
   !! @param[in]  ax1    Semi-axis of the ellipse along the major direction
   !!                    before rotation.
   !! @param[in]  ax2    Semi-axis of the ellipse along the minor direction
   !!                    before rotation.
   !! @param[in]  angle  Rotation angle of the ellipse, in degrees.
   !! @param[out] xe     X coordinates of the discretized ellipse boundary.
   !! @param[out] ye     Y coordinates of the discretized ellipse boundary.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine ellipse(xc, yc, ax1, ax2, angle, xe, ye)

      USE parameters, ONLY : X_circle, Y_circle
      USE parameters, ONLY : npoints

      implicit none

      ! Input parameters
      real(wp), intent(in) :: xc, yc
      real(wp), intent(in) :: ax1, ax2
      real(wp), intent(in) :: angle

      ! Output parameters
      real(wp), intent(out) :: xe(npoints), ye(npoints)

      ! Local variables
      real(wp) :: cos_angle, sin_angle

      ! Compute the sine and cosine of the angle
      cos_angle = cosd(angle)
      sin_angle = sind(angle)

      ! Compute the rotated ellipse coordinates directly, avoiding
      ! temporary arrays for the scaled unit-circle coordinates
      xe(1:npoints) = xc + ax1 * X_circle(1:npoints) * cos_angle -      &
         ax2 * Y_circle(1:npoints) * sin_angle

      ye(1:npoints) = yc + ax1 * X_circle(1:npoints) * sin_angle +      &
         ax2 * Y_circle(1:npoints) * cos_angle

      RETURN

   end subroutine ellipse

   !***********************************************************************
   !> @brief Compute the fraction of each local cell covered by the ellipse.
   !!
   !! This routine evaluates the fraction of area covered by the ellipse in
   !! each cell of a local window. The coverage is estimated using the
   !! precomputed quadrature/sample points stored in xv and yv.
   !!
   !! Compared with the original implementation, this version avoids the
   !! allocation and traversal of large temporary 2D arrays. The test for
   !! point inclusion inside the ellipse is performed on the fly, and the
   !! number of points inside the ellipse is accumulated directly for each
   !! local cell.
   !!
   !! @param[in]  Xc_local    Local X coordinates of the cell centers.
   !! @param[in]  Yc_local    Local Y coordinates of the cell centers.
   !! @param[in]  xc_e        X coordinate of the ellipse center.
   !! @param[in]  yc_e        Y coordinate of the ellipse center.
   !! @param[in]  ax1         Semi-axis of the ellipse along the major axis.
   !! @param[in]  ax2         Semi-axis of the ellipse along the minor axis.
   !! @param[in]  angle       Rotation angle of the ellipse, in degrees.
   !! @param[out] area_fract  Fraction of each local cell covered by the
   !!                         ellipse.
   !! @param[in]  nx_cell     Number of local cells in the X direction.
   !! @param[in]  ny_cell     Number of local cells in the Y direction.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   SUBROUTINE local_intersection(Xc_local, Yc_local, xc_e, yc_e, ax1, ax2, angle,&
      area_fract, nx_cell, ny_cell)

      USE parameters, ONLY : nv2, inv_nv2

      IMPLICIT NONE
      ! Input parameters
      REAL(wp), INTENT(in) :: Xc_local(:,:), Yc_local(:,:)
      REAL(wp), INTENT(in) :: xc_e, yc_e, ax1, ax2, angle
      INTEGER, INTENT(in) :: nx_cell, ny_cell

      ! Output parameter
      REAL(wp), INTENT(out) :: area_fract(max_cells,max_cells)

      ! Local variables
      REAL(wp) :: c, s, c1, s1, c2, s2
      REAL(wp) :: c1xv_p_s1yv(nv2), c2yv_m_s2xv(nv2)
      REAL(wp) :: c1xv_p_s1yv_2(nv2), c2yv_m_s2xv_2(nv2)
      REAL(wp) :: alpha_e, beta_e
      REAL(wp) :: xc_i, yc_i
      REAL(wp) :: shift1, shift2, base_term, term_val
      INTEGER :: i, j, k, n_inside
      REAL(wp) :: a_k, b_k
      REAL(wp) :: u, v

      ! Compute cosine and sine of the angle
      c = cosd(angle)
      s = sind(angle)

      ! Compute coefficients
      c1 = c / ax1
      s1 = s / ax1
      c2 = c / ax2
      s2 = s / ax2

      ! Precompute the contribution of the ellipse center
      alpha_e = c1 * xc_e + s1 * yc_e
      beta_e  = c2 * yc_e - s2 * xc_e

      ! Precompute the terms depending only on the sample-point coordinates
      c1xv_p_s1yv = c1 * xv + s1 * yv - alpha_e
      c2yv_m_s2xv = c2 * yv - s2 * xv - beta_e

      ! Precompute the squared terms depending only on the sample-point coordinates
      c1xv_p_s1yv_2 = c1xv_p_s1yv * c1xv_p_s1yv
      c2yv_m_s2xv_2 = c2yv_m_s2xv * c2yv_m_s2xv

      ! For each local cell, count directly how many sample points fall
      ! inside the ellipse
      DO j = 1, nx_cell
         DO i = 1, ny_cell

            xc_i = Xc_local(i,j)
            yc_i = Yc_local(i,j)

            u = c1 * xc_i + s1 * yc_i
            v = yc_i * c2 - xc_i * s2

            shift1 = 2.0_wp * u
            shift2 = 2.0_wp * v

            base_term = u * u + v * v

            n_inside = 0

            DO k = 1, nv2

               a_k = c1xv_p_s1yv(k)
               b_k = c2yv_m_s2xv(k)

               term_val = c1xv_p_s1yv_2(k) + shift1 * a_k +                     &
                  c2yv_m_s2xv_2(k) + shift2 * b_k + base_term

               IF (term_val <= 1.0_wp) n_inside = n_inside + 1

            END DO

            ! Convert the number of inside points into area fraction
            area_fract(i,j) = REAL(n_inside, wp) * inv_nv2

         END DO
      END DO

      RETURN

   end subroutine local_intersection

   !***********************************************************************
   !> @brief Rasterize a lobe onto a local grid window.
   !!
   !! Computes the discretized footprint of a lobe centered at `(x_i, y_i)`
   !! with semi-axes `x1_i` and `x2_i`, rotated by `angle_i`, and maps it
   !! onto a local subset of the computational grid.
   !!
   !! The subroutine first generates the ellipse boundary, then determines
   !! the corresponding grid-aligned bounding box, and finally evaluates
   !! the fraction of each local cell covered by the lobe. It also builds
   !! an integer coverage mask and initializes the local distance array for
   !! the covered cells using the input integer distance `dist_int_i`.
   !!
   !! Cells intersected by the lobe are assigned `Zflow_local_int = 1`,
   !! while uncovered cells are assigned `0`. The array `Dist_local` is
   !! initialized to `dist_int_i` where the lobe covers the cell and to a
   !! large default value elsewhere.
   !!
   !! @param[in]  x_i              X coordinate of the lobe center.
   !! @param[in]  y_i              Y coordinate of the lobe center.
   !! @param[in]  x1_i             Semi-axis of the lobe along the major
   !!                              direction before rotation.
   !! @param[in]  x2_i             Semi-axis of the lobe along the minor
   !!                              direction before rotation.
   !! @param[in]  angle_i          Rotation angle of the lobe, in degrees.
   !! @param[in]  dist_int_i       Integer distance value assigned to cells
   !!                              covered by the lobe.
   !! @param[out] i_West           Western grid index of the local bounding
   !!                              box.
   !! @param[out] i_East           Eastern grid index of the local bounding
   !!                              box.
   !! @param[out] j_South          Southern grid index of the local bounding
   !!                              box.
   !! @param[out] j_North          Northern grid index of the local bounding
   !!                              box.
   !! @param[out] Zflow_local      Local array containing the fraction of
   !!                              each cell covered by the lobe.
   !! @param[out] Dist_local       Local integer array containing the lobe
   !!                              distance values for the covered cells.
   !! @param[out] Zflow_local_int  Local integer mask of lobe coverage
   !!                              (`1` for covered cells, `0` otherwise).
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   SUBROUTINE rasterize(x_i, y_i, x1_i, x2_i, angle_i, dist_int_i, i_West,       &
      i_East, j_South, j_North, Zflow_local, Dist_local, Zflow_local_int)

      USE parameters, only : Xtopo, Ytopo
      USE parameters, only : npoints

      IMPLICIT NONE

      ! Input parameters
      REAL(wp), INTENT(in) :: x_i, y_i, x1_i, x2_i, angle_i
      INTEGER, INTENT(in) :: dist_int_i

      ! Output parameters
      INTEGER, INTENT(out) :: i_West, i_East, j_South, j_North
      REAL(wp),INTENT(out) :: Zflow_local(max_cells,max_cells)
      INTEGER, INTENT(out) :: Dist_local(max_cells,max_cells)
      INTEGER, INTENT(out) :: Zflow_local_int(max_cells,max_cells)

      ! Local variables
      REAL(wp) :: xe(npoints), ye(npoints)
      INTEGER :: nx_local, ny_local

      ! Compute the points of the lobe
      CALL ellipse(x_i, y_i, x1_i, x2_i, angle_i, xe, ye)

      ! Compute the bounding box for the new lobe
      CALL bounding_box(xe, ye, i_West, i_East, j_South, j_North)

      ! Define the subgrid of pixels to check for coverage
      nx_local = i_East - i_West
      ny_local = j_North - j_South

      ! Compute the fraction of cells covered by the lobe
      CALL local_intersection( Xtopo(j_South:j_North-1, i_West:i_East-1),             &
         Ytopo(j_South:j_North-1, i_West:i_East-1), x_i, y_i, x1_i, x2_i,           &
         angle_i, Zflow_local, nx_local, ny_local)

      ! Compute the integer version (0 = pixel not covered by lobe, 1 = covered)
      Zflow_local_int(1:ny_local,1:nx_local) =                                    &
         ceiling(Zflow_local(1:ny_local,1:nx_local))

      ! Compute the new minimum "lobe distance" of the pixels from the vent
      Dist_local(1:ny_local,1:nx_local) =                                         &
         MERGE(dist_int_i, 9999, Zflow_local_int(1:ny_local,1:nx_local) == 1)

      RETURN

   END SUBROUTINE rasterize

   !***********************************************************************
   !> @brief Select the index of the parent lobe for the next emplacement step.
   !!
   !! Chooses the index of the parent lobe from the set of already
   !! generated lobes according to a probability law controlled by
   !! `lobe_exponent`.
   !!
   !! A random number is transformed by the exponent-based weighting to
   !! bias the selection toward either younger or older lobes, depending on
   !! the model settings. If `force_max_length` is enabled, the selection is
   !! restricted to lobes whose integer distance is smaller than
   !! `max_length`. If `start_from_dist_flag` is enabled, the probability
   !! law is applied after sorting lobes by distance from the vent.
   !!
   !! The selected index is returned in `idx` and is used as the parent
   !! lobe for subsequent growth.
   !!
   !! @param[in]  i        Number of candidate lobes available for
   !!                      selection.
   !! @param[in]  distInt  Integer array containing the distance-based
   !!                      measure associated with each candidate lobe.
   !! @param[out] idx      Index of the selected parent lobe.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step0(i, distInt, idx)

      USE parameters, ONLY : lobe_exponent
      USE parameters, ONLY : force_max_length, start_from_dist_flag
      USE parameters, ONLY : max_length

      implicit none
      integer, intent(in) :: i
      integer, intent(in) :: distInt(i)
      integer, intent(out) :: idx

      real(wp) :: idx0, idx1, idx2
      integer :: idx3, sorted_dist(i)
      integer :: mask(i)

      ! Generate a random number between 0 and 1
      call random_number(idx0)

      idx1 = idx0**lobe_exponent

      if (force_max_length) then
         ! The parent lobe is chosen only among those with dist smaller than
         ! max_length

         mask = merge(1, 0,distInt < max_length)
         ! mask = distInt < max_length
         idx2 = sum(mask) * idx1
         idx3 = ceiling(idx2)
         idx = int(idx3)

         ! Sort distInt and find corresponding index
         call argsort(distInt, sorted_dist)
         idx = sorted_dist(idx)
      else
         ! The parent lobe is chosen among all the lobes
         idx2 = i * idx1
         idx = int(floor(idx2))
      end if

      if (start_from_dist_flag) then
         ! The probability law is associated with the distance from the vent
         call argsort(distInt, sorted_dist)
         idx = sorted_dist(idx)
      end if

      RETURN

   end subroutine step0

   !***********************************************************************
   !> @brief Compute local slope and downslope direction for a new lobe.
   !!
   !! This routine interpolates the elevation at the lobe center and along
   !! the boundary of the ellipse representing the lobe footprint. The point
   !! on the ellipse with minimum elevation is identified and used to compute
   !! both the local slope magnitude and the azimuth of the maximum
   !! downslope direction.
   !!
   !! @param[in]  xi               X coordinate of the lobe center in grid
   !!                              coordinates.
   !! @param[in]  ix               X index of the cell containing the lobe
   !!                              center.
   !! @param[in]  yi               Y coordinate of the lobe center in grid
   !!                              coordinates.
   !! @param[in]  iy               Y index of the cell containing the lobe
   !!                              center.
   !! @param[in]  x_idx            X coordinate of the lobe center in map
   !!                              coordinates.
   !! @param[in]  y_idx            Y coordinate of the lobe center in map
   !!                              coordinates.
   !! @param[in]  ax1              Semi-axis of the lobe along the major
   !!                              direction.
   !! @param[in]  ax2              Semi-axis of the lobe along the minor
   !!                              direction.
   !! @param[in]  angle            Rotation angle of the lobe, in degrees.
   !! @param[out] slope            Local slope magnitude computed from the
   !!                              center-to-boundary elevation drop.
   !! @param[out] max_slope_angle  Azimuth of the maximum downslope direction,
   !!                              in degrees.
   !! @param[out] zidx             Interpolated elevation at the lobe center.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step1(xi, ix, yi, iy, x_idx, y_idx, ax1, ax2, angle, slope,        &
      max_slope_angle, zidx)

      USE parameters, ONLY : xcmin, ycmin
      USE parameters, ONLY : npoints

      implicit none
      ! Input variables
      real(wp), intent(in) :: xi, yi, x_idx, y_idx
      integer, intent(in) :: ix, iy
      real(wp), intent(in) :: ax1, ax2, angle

      ! Output variables
      real(wp), intent(out) :: slope, max_slope_angle, zidx

      ! Local variables
      integer :: ix1, iy1, i, i_min
      real(wp) :: xi_fract, yi_fract
      real(wp) :: xe(npoints), ye(npoints), ze(npoints)

      real(wp) :: xei, yei
      integer :: ixe, iye, ixe1, iye1
      real(wp) :: xei_fract, yei_fract

      real(wp) :: Fx_lobe, Fy_lobe
      real(wp) :: ze_min

      ! Incremented indices
      ix1 = ix + 1
      iy1 = iy + 1

      ! Compute the barycentric coordinates of the lobe center within the pixel
      xi_fract = xi - ix + 1.0_wp
      yi_fract = yi - iy + 1.0_wp

      ! Interpolate the elevation at the pixel corners to obtain the elevation
      ! at the lobe center
      zidx = xi_fract * (yi_fract * Ztot(iy1, ix1) +                              &
         (1.0_wp - yi_fract) * Ztot(iy, ix1)) +                                   &
         (1.0_wp - xi_fract) * (yi_fract * Ztot(iy1, ix) +                        &
         (1.0_wp - yi_fract) * Ztot(iy, ix))

      ! Compute the points of the lobe boundary
      call ellipse(x_idx, y_idx, ax1, ax2, angle, xe, ye)

      ! Initialize the minimum elevation found along the ellipse boundary
      ze_min = huge(1.0_wp)
      i_min = 1

      ! Interpolate the topography at the ellipse boundary points and track
      ! the point with minimum elevation while scanning the boundary
      DO i = 1, npoints

         ! Compute the indices of the pixel containing the current ellipse point
         xei = (xe(i) - xcmin) * inv_cell
         yei = (ye(i) - ycmin) * inv_cell

         ixe = ceiling(xei)
         iye = ceiling(yei)

         ! Compute the local coordinates of the point within the containing pixel
         xei_fract = xei - ixe + 1.0_wp
         yei_fract = yei - iye + 1.0_wp

         ixe1 = ixe + 1
         iye1 = iye + 1

         ! Bilinear interpolation of the topography at the ellipse point
         ze(i) = xei_fract * (yei_fract * Ztot(iye1, ixe1) +                      &
            (1.0_wp - yei_fract) * Ztot(iye, ixe1)) +                             &
            (1.0_wp - xei_fract) * (yei_fract * Ztot(iye1, ixe) +                 &
            (1.0_wp - yei_fract) * Ztot(iye, ixe))

         ! Update the minimum boundary elevation and its index
         if (ze(i) < ze_min) then
            ze_min = ze(i)
            i_min = i
         end if

      END DO

      ! Compute the vector from the lobe center to the boundary point with
      ! minimum elevation
      Fx_lobe = x_idx - xe(i_min)
      Fy_lobe = y_idx - ye(i_min)

      ! Compute the local slope magnitude and the maximum downslope direction
      slope = max(0.0_wp, (zidx - ze_min) / sqrt(Fx_lobe**2 + Fy_lobe**2))
      max_slope_angle = mod(180.0_wp + atan2d(Fy_lobe, Fx_lobe), 360.0_wp)

      RETURN

   end subroutine step1

   !***********************************************************************
   !> @brief Compute the propagation angle of a new lobe.
   !!
   !! Determines the emplacement direction of a new lobe starting from the
   !! local maximum downslope direction `max_slope_angle` and the local
   !! slope magnitude `slope`.
   !!
   !! By default, the new angle coincides with the maximum downslope
   !! direction. If `max_slope_prob` is smaller than 1, a random angular
   !! perturbation is added. For positive slope and nonzero
   !! `max_slope_prob`, the perturbation is sampled from a zero-mean normal
   !! distribution whose spread depends on both `slope` and
   !! `max_slope_prob`. For zero slope or zero `max_slope_prob`, the
   !! perturbation is sampled uniformly.
   !!
   !! @param[in]  slope            Local topographic slope magnitude.
   !! @param[in]  max_slope_angle  Azimuth of the maximum downslope
   !!                              direction, in degrees.
   !! @param[out] new_angle        Propagation angle assigned to the new
   !!                              lobe, in degrees.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step2(slope, max_slope_angle, new_angle)

      USE parameters, ONLY : max_slope_prob
      implicit none

      ! Inputs
      real(wp), intent(in) :: slope, max_slope_angle

      ! Outputs
      real(wp), intent(out) :: new_angle

      ! Local variables
      real(wp) :: slopedeg, sigma, rand(2), rand_angle_new
      logical :: check_flag

      ! Default to the unperturbed angle
      new_angle = max_slope_angle

      IF (max_slope_prob < 1.0_wp) THEN

         ! Convert slope to degrees
         slopedeg = atand(slope)

         IF (slopedeg > 0.0_wp .and. max_slope_prob > 0.0_wp) THEN

            sigma = (1.0_wp-max_slope_prob) / max_slope_prob * (90.0_wp-slopedeg) &
               / slopedeg

            check_flag = .TRUE.
            DO WHILE (check_flag)

               ! Generate a random normal value
               rand_angle_new = sigma * rnorm_box_muller_single_variate()

               ! Check if the angle is within bounds
               IF (-180.0_wp<=rand_angle_new .AND. rand_angle_new<=180.0_wp) THEN

                  check_flag = .FALSE.

               END IF

            END DO

         ELSE

            ! Generate a uniform random value
            CALL random_number(rand)
            rand_angle_new = 360.0_wp * ABS(rand(1) - 0.5_wp)

         END IF

         ! Compute the new angle
         new_angle = max_slope_angle + rand_angle_new

      END IF

      RETURN

   end subroutine step2

   !***********************************************************************
   !> @brief Apply the inertia effect to compute the new propagation angle.
   !!
   !! Combines the propagation direction inherited from the parent lobe
   !! with the local downslope direction to obtain the final direction of
   !! the new lobe after accounting for inertia.
   !!
   !! The parent-lobe direction is provided by `angle_idx`, while the local
   !! downslope direction is provided by `old_angle`. The relative weight of
   !! the two directions is controlled by the local slope and by the model
   !! parameter `inertial_exponent`. For zero inertia exponent, the new
   !! direction coincides with the downslope direction. Otherwise, the two
   !! unit vectors are averaged using an inertia coefficient that decreases
   !! with increasing slope.
   !!
   !! The subroutine also returns the cosine and sine of the parent-lobe
   !! direction, which are used in the following emplacement steps.
   !!
   !! @param[in]  angle_idx   Propagation angle of the parent lobe, in
   !!                         degrees.
   !! @param[in]  old_angle   Local downslope direction, in degrees.
   !! @param[in]  slope       Local topographic slope magnitude.
   !! @param[out] cos_angle1  Cosine of the parent-lobe propagation angle.
   !! @param[out] sin_angle1  Sine of the parent-lobe propagation angle.
   !! @param[out] new_angle   Propagation angle of the new lobe after
   !!                         applying the inertia effect, in degrees.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step3(angle_idx,  old_angle, slope, cos_angle1, sin_angle1,        &
      new_angle)

      USE parameters, ONLY : inertial_exponent
      USE parameters, ONLY : pi
      USE parameters, ONLY : eps

      implicit none
      ! Input variables
      real(wp), intent(in) :: angle_idx,  old_angle, slope

      ! Output variables
      real(wp), intent(out) :: cos_angle1, sin_angle1, new_angle

      ! Local variables
      real(wp) :: cos_angle2, sin_angle2, alfa_inertial, x_avg, y_avg

      ! STEP 3: ADD THE EFFECT OF INERTIA
      ! Cosine and sine of the angle of the parent lobe
      cos_angle1 = cosd(angle_idx)
      sin_angle1 = sind(angle_idx)

      ! Cosine and sine of the angle of maximum slope
      cos_angle2 = cosd(old_angle)
      sin_angle2 = sind(old_angle)

      if ( abs(inertial_exponent-0.0_wp) <= eps ) then

         alfa_inertial = 0.0_wp

      else

         alfa_inertial = (1.0_wp - (2.0_wp * atan(slope)/pi)**inertial_exponent)  &
            **(1.0_wp / inertial_exponent)

      end if

      ! Average angles using inertia effect
      x_avg = (1.0_wp - alfa_inertial) * cos_angle2 + alfa_inertial * cos_angle1
      y_avg = (1.0_wp - alfa_inertial) * sin_angle2 + alfa_inertial * sin_angle1

      ! Calculate the new angle

      new_angle = modulo( atan2d(y_avg, x_avg), 360.0_wp)

      RETURN

   end subroutine step3

   !***********************************************************************
   !> @brief Compute the position and geometry of a new budded lobe.
   !!
   !! Determines the budding point on the boundary of the parent lobe in
   !! the direction `new_angle`, evaluates the local topographic slope at
   !! that point, and computes the center coordinates and semi-axes of the
   !! new lobe.
   !!
   !! The budding point is obtained by intersecting the parent ellipse,
   !! defined by semi-axes `x1_idx` and `x2_idx` and orientation
   !! `angle_idx`, with the line directed along `new_angle`. The resulting
   !! offset is rotated into the global coordinate system using
   !! `cos_angle1` and `sin_angle1`.
   !!
   !! If the budding point is too close to the computational-domain
   !! boundary, the subroutine sets `check_step = .FALSE.` and returns zero
   !! values for the new lobe properties. Otherwise, it interpolates the
   !! topographic elevation at the budding point, computes the local slope
   !! between the parent-lobe center and the budding point, evaluates the
   !! semi-axes of the new lobe through `compute_semiaxis`, and finally
   !! places the new lobe center at a distance controlled by `dist_fact`.
   !!
   !! @param[in]  new_angle      Propagation angle of the new lobe, in
   !!                            degrees.
   !! @param[in]  angle_idx      Orientation angle of the parent lobe, in
   !!                            degrees.
   !! @param[in]  x1_idx         Major semi-axis of the parent lobe.
   !! @param[in]  x2_idx         Minor semi-axis of the parent lobe.
   !! @param[in]  x_idx          X coordinate of the parent-lobe center.
   !! @param[in]  y_idx          Y coordinate of the parent-lobe center.
   !! @param[in]  zidx           Interpolated elevation at the parent-lobe
   !!                            center.
   !! @param[in]  cos_angle1     Cosine of the parent-lobe orientation.
   !! @param[in]  sin_angle1     Sine of the parent-lobe orientation.
   !! @param[out] check_step     Logical flag indicating whether the new
   !!                            lobe can be placed inside the valid domain.
   !! @param[out] x_new          X coordinate of the new lobe center.
   !! @param[out] y_new          Y coordinate of the new lobe center.
   !! @param[out] new_x1         Major semi-axis of the new lobe.
   !! @param[out] new_x2         Minor semi-axis of the new lobe.
   !! @param[out] new_angle_out  Final orientation angle assigned to the new
   !!                            lobe, in degrees.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine step4and5(new_angle, angle_idx, x1_idx, x2_idx, x_idx, y_idx,      &
      zidx, cos_angle1, sin_angle1, check_step, x_new, y_new, new_x1, new_x2,  &
      new_angle_out)

      USE parameters, ONLY : dist_fact
      USE parameters, ONLY : xcmin, ycmin, nx, ny

      implicit none

      ! Input variables
      REAL(wp), INTENT(IN) :: new_angle, angle_idx, x1_idx, x2_idx
      REAL(wp), INTENT(IN) :: x_idx, y_idx, zidx
      REAL(wp), INTENT(IN) :: cos_angle1, sin_angle1

      ! Output variables
      LOGICAL, INTENT(out) :: check_step
      real(wp), INTENT(out) :: x_new, y_new, new_x1, new_x2, new_angle_out

      ! Local variables
      REAL(wp) :: a, xt, yt, delta_x, delta_y, xi, yi
      REAL(wp) :: xi_fract, yi_fract, ze, slope
      INTEGER :: ix, iy, ix1, iy1
      REAL(wp) :: v1, v2, v
      REAL(wp) :: x1_2 , x2_2

      ! Calculate the angular coefficient 'a' of the line
      a = tand(new_angle - angle_idx)

      x1_2 = x1_idx**2
      x2_2 = x2_idx**2

      ! Calculate xt based on the direction of the new lobe
      IF (cosd(new_angle - angle_idx) > 0.0_wp) THEN

         xt = SQRT(x1_2 * x2_2 / (x2_2 + x1_2 * a**2))

      ELSE

         xt = -SQRT(x1_2 * x2_2 / (x2_2 + x1_2 * a**2))

      END IF

      ! Calculate yt
      yt = a * xt

      ! Calculate delta_x and delta_y based on rotation
      delta_x = xt * cos_angle1 - yt * sin_angle1
      delta_y = xt * sin_angle1 + yt * cos_angle1

      ! Convert coordinates to index values
      CALL coorToIdx(x_idx + delta_x, xcmin, inv_cell, ix, xi)
      CALL coorToIdx(y_idx + delta_y, ycmin, inv_cell, iy, yi)

      ix1 = ix + 1
      iy1 = iy + 1

      ! Check stopping condition (lobe close to domain boundary)
      if (ix <= 0.5_wp * max_cells .or. ix1 >= nx - 0.5_wp * max_cells .or.       &
         iy <= 0.5_wp * max_cells .or. iy1 >= ny - 0.5_wp * max_cells) then

         WRITE(*,*) 'ERROR : the lava has reached the DEM margin'
         IF (ix <= 0.5 * max_cells) WRITE(*,*) 'Please increase west_to_vent'
         IF (ix1 >= (nx - 0.5*max_cells)) WRITE(*,*) 'Please increase east_to_vent'
         IF (iy <= 0.5 * max_cells) WRITE(*,*) 'Please increase south_to_vent'
         IF (iy1 >= (ny - 0.5*max_cells)) WRITE(*,*) 'Please increase north_to_vent'

         check_step = .FALSE.
         x_new = 0.0_wp
         y_new = 0.0_wp
         new_x1 = 0.0_wp
         new_x2 = 0.0_wp
         new_angle_out = 0.0_wp

      else

         check_step = .TRUE.  ! default value when no stopping condition is met

         xi_fract = xi - ix + 1.0_wp
         yi_fract = yi - iy + 1.0_wp

         ! Interpolate Ztot at the new budding point
         ze = xi_fract * (yi_fract * Ztot(iy1, ix1) +                             &
            (1.0_wp - yi_fract) * Ztot(iy, ix1)) +                              &
            (1.0_wp - xi_fract) * (yi_fract * Ztot(iy1, ix) +                   &
            (1.0_wp - yi_fract) * Ztot(iy, ix))

         ! Calculate the slope
         slope = max(0.0_wp, (zidx - ze) / sqrt(delta_x**2 + delta_y**2))

         ! Compute the semi-axes of the new lobe
         CALL compute_semiaxis(slope,new_x1, new_x2)

         ! Calculate v1 and v2
         v1 = sqrt(delta_x**2 + delta_y**2)
         v2 = v1 + new_x1

         ! Calculate v
         v = (v1 * (1.0_wp - dist_fact) + v2 * dist_fact) / v1

         ! Compute the new lobe center coordinates
         x_new = x_idx + v * delta_x
         y_new = y_idx + v * delta_y
         new_angle_out = new_angle

      end if

      RETURN

   end subroutine step4and5


   !***********************************************************************
   !> @brief Return the indices that sort an array in ascending order.
   !!
   !! Computes the permutation of indices that orders the input array from
   !! the smallest value to the largest one, without modifying the input
   !! array itself.
   !!
   !! The output array `sorted_indices` contains the positions of the
   !! elements of `array` in ascending sorted order, so that
   !! `array(sorted_indices)` is the sorted version of `array`.
   !!
   !! @param[in]  array           Input array to be sorted indirectly.
   !! @param[out] sorted_indices  Indices that sort `array` in ascending
   !!                             order.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   subroutine argsort(array, sorted_indices)
      implicit none
      integer, intent(in) :: array(:)
      integer, intent(out) :: sorted_indices(size(array))
      integer :: i, j, n
      integer :: temp_idx

      n = size(array)
      do i = 1, n
         sorted_indices(i) = i
      end do

      ! Simple bubble sort for demonstration; replace with more efficient
      ! algorithm if needed
      do i = 1, n-1
         do j = i+1, n
            if (array(sorted_indices(i)) > array(sorted_indices(j))) then
               temp_idx = sorted_indices(i)
               sorted_indices(i) = sorted_indices(j)
               sorted_indices(j) = temp_idx
            end if
         end do
      end do
   end subroutine argsort

   !***********************************************************************
   !> @brief Generate a single normally distributed random variate.
   !!
   !! Returns one pseudo-random variate drawn from a standard normal
   !! distribution using the Box-Muller transform.
   !!
   !! The function generates two independent uniformly distributed random
   !! numbers in the interval `(0, 1)` and transforms them into a single
   !! Gaussian-distributed variate with zero mean and unit variance.
   !!
   !! @return variate Single pseudo-random variate from a standard normal
   !!                 distribution.
   !!
   !! @date 2026-04-02
   !! @author M. de' Michieli Vitturi
   !! @author S. Tarquini
   !***********************************************************************
   function rnorm_box_muller_single_variate() result(variate)

      USE parameters, ONLY : pi

      implicit none

      ! return a standard normal variate
      real(wp) :: variate
      real(wp) :: u(2), factor, arg

      call random_number(u)
      factor = sqrt(-2.0_wp * log(u(1)))
      arg = 2.0_wp * pi *u(2)
      variate = factor * cos(arg)

   end function rnorm_box_muller_single_variate

END MODULE flow
