!********************************************************************************
!> \brief Input/Output module
!
!> This module contains all the input/output subroutine and the 
!> realted variables.
!
!> Copyright: M. de' Michieli Vitturi, S. Tarquini
!> All copyright notices within source files and as generated by
!> the Software as output must be retained, unchanged.
!
!> \date 2024/08/20
!> \author Mattia de' Michieli Vitturi
!> \author Simone Tarquini
!
!********************************************************************************

MODULE inpout

  USE parameters

  IMPLICIT NONE

  !> Flag for the output in NetCDF format
  !> - T      => netCDF4 file saved (.nc)
  !> - F      => not saved
  !> .
  LOGICAL :: nc_flag

  !> Flag for the output in ESRI raster format
  !> - T      => ascii file saved (.asc)
  !> - F      => not saved
  !> .
  LOGICAL :: asc_flag

  CHARACTER(LEN=40) :: input_file         !< File with the run parameters
  CHARACTER(LEN=40) :: backup_file        !< Bakcup File with the run parameters
  CHARACTER(LEN=40) :: union_diff_file    !< File with previous output to compare
  INTEGER, PARAMETER :: input_unit = 7       !< Input data unit
  INTEGER, PARAMETER :: topo_unit = 8        !< Topography DEM unit
  INTEGER, PARAMETER :: backup_unit = 9      !> Input Backup data unit
  INTEGER, PARAMETER :: restart_unit = 10
  INTEGER, PARAMETER :: output_unit = 11
  INTEGER, PARAMETER :: asc_unit = 12

  INTEGER :: cols, rows

  NAMELIST / run_parameters / run_name, source, vent_flag, crop_flag,           &
       hazard_flag, volume_flag, fixed_dimension_flag, topo_mod_flag,           &
       restart_flag, nc_flag , asc_flag, union_diff_flag

  NAMELIST / vent_parameters / n_vents, x_vent, y_vent , x_vent_end , y_vent_end

  NAMELIST / crop_parameters / east_to_vent, west_to_vent, south_to_vent,       &
       north_to_vent

  NAMELIST / flow_parameters / n_flows, min_n_lobes, max_n_lobes, total_volume, &
       lobe_area, avg_lobe_thickness, thickness_ratio , thickening_parameter,   &
       lobe_exponent, max_slope_prob, inertial_exponent , n_init , dist_fact,   &
       aspect_ratio_coeff, max_aspect_ratio, a_beta, b_beta

  NAMELIST / restart_parameters / n_restarts, restart_files,                    &
       restart_filling_parameters

  NAMELIST / numerical_parameters / npoints, nv

  NAMELIST / union_diff_parameters / union_diff_file

CONTAINS

  !******************************************************************************
  !> \brief Initialization of the variables read from the input file
  !
  !> This subroutine initialize the input variables with default values.
  !
  !> @author 
  !> Mattia de' Michieli Vitturi
  !> \date 2024/08/20
  !
  !******************************************************************************

  SUBROUTINE init_param  

    IMPLICIT none

    nc_flag = .FALSE.
    asc_flag = .TRUE.

    vent_flag = -1

    union_diff_flag = .FALSE.

    n_vents = -9999

    ALLOCATE(x_vent(20))
    ALLOCATE(y_vent(20))
    x_vent(:) = -9999.0_wp
    y_vent(:) = -9999.0_wp

    ALLOCATE(x_vent_end(20))
    ALLOCATE(y_vent_end(20))
    x_vent_end(:) = -9999.0_wp
    y_vent_end(:) = -9999.0_wp

    
    east_to_vent = -9999.0_wp
    west_to_vent = -9999.0_wp
    south_to_vent = -9999.0_wp
    north_to_vent = -9999.0_wp

    n_flows = -9999
    min_n_lobes = -9999
    max_n_lobes = -9999
    total_volume = -9999.0_wp
    lobe_area = -9999.0_wp
    avg_lobe_thickness = -9999.0_wp
    thickness_ratio = -9999.0_wp
    thickening_parameter = -9999.0_wp
    lobe_exponent = -9999.0_wp
    max_slope_prob = -9999.0_wp
    inertial_exponent = -9999.0_wp
    n_init = -9999
    dist_fact = -9999.0_wp
    aspect_ratio_coeff = -9999.0_wp
    max_aspect_ratio = -9999.0_wp
    npoints = -9999

    a_beta = -9999.0_wp
    b_beta = -9999.0_wp

    n_restarts = -9999
    ALLOCATE(restart_files(20))
    ALLOCATE(restart_filling_parameters(20))

    force_max_length = .FALSE.
    start_from_dist_flag = .FALSE.
    max_length = 50


  END SUBROUTINE init_param

  SUBROUTINE read_param

    IMPLICIT NONE

    INTEGER :: ios
    LOGICAL :: lexist
    LOGICAL :: condition

    CHARACTER(LEN=40) :: base_name

    REAL(wp), ALLOCATABLE :: x_vent_temp(:)
    REAL(wp), ALLOCATABLE :: y_vent_temp(:)

    REAL(wp), ALLOCATABLE :: x_vent_end_temp(:)
    REAL(wp), ALLOCATABLE :: y_vent_end_temp(:)
    
    CHARACTER(LEN = 40), ALLOCATABLE :: restart_files_temp(:)
    REAL(wp), ALLOCATABLE :: restart_filling_parameters_temp(:)

    INTEGER :: i    !< loop counter

    LOGICAL :: tend1 
    CHARACTER(LEN=80) :: card

    input_file = 'mr_lava_loba.inp'

    INQUIRE (FILE=input_file,exist=lexist)

    IF (lexist .EQV. .FALSE.) THEN

       WRITE(*,*) 'Input file IMEX_SfloW2D.inp not found'
       STOP

    END IF

    OPEN(input_unit,FILE=input_file,STATUS='old')

    ! ---------- READ run_parameters NAMELIST -----------------------------------
    READ(input_unit, run_parameters,IOSTAT=ios )

    IF ( ios .NE. 0 ) THEN

       WRITE(*,*) 'IOSTAT=',ios
       WRITE(*,*) 'ERROR: problem with namelist RUN_PARAMETERS'
       WRITE(*,*) 'Please check the input file'
       WRITE(*,run_parameters)
       STOP

    ELSE

       WRITE(*,*) 'Run name: ',run_name
       REWIND(input_unit)

    END IF

    ! ---------- READ vent_parameters NAMELIST -----------------------------------
    READ(input_unit, vent_parameters,IOSTAT=ios )

    IF ( ios .NE. 0 ) THEN

       WRITE(*,*) 'IOSTAT=',ios
       WRITE(*,*) 'ERROR: problem with namelist VENT_PARAMETERS'
       WRITE(*,*) 'Please check the input file'
       WRITE(*,vent_parameters)
       STOP

    ELSE

       ALLOCATE(x_vent_temp(n_vents))
       ALLOCATE(y_vent_temp(n_vents))

       x_vent_temp(1:n_vents) = x_vent(1:n_vents)
       y_vent_temp(1:n_vents) = y_vent(1:n_vents)

       DEALLOCATE(x_vent)
       DEALLOCATE(y_vent)

       ALLOCATE(x_vent(n_vents))
       ALLOCATE(y_vent(n_vents))

       x_vent(:) = x_vent_temp(:)
       y_vent(:) = y_vent_temp(:)

       DEALLOCATE(x_vent_temp)
       DEALLOCATE(y_vent_temp)

       WRITE(*,*) 'x_vent ',x_vent 
       WRITE(*,*) 'y_vent ',y_vent 

       IF ( ABS(x_vent_end(1) - (-9999.0_wp) )>= eps ) THEN

          ALLOCATE(x_vent_end_temp(n_vents))
          ALLOCATE(y_vent_end_temp(n_vents))
          
          x_vent_end_temp(1:n_vents) = x_vent_end(1:n_vents)
          y_vent_end_temp(1:n_vents) = y_vent_end(1:n_vents)
          
          DEALLOCATE(x_vent_end)
          DEALLOCATE(y_vent_end)

          ALLOCATE(x_vent_end(n_vents))
          ALLOCATE(y_vent_end(n_vents))

          x_vent_end_temp(1:n_vents) = x_vent_end(1:n_vents)
          y_vent_end_temp(1:n_vents) = y_vent_end(1:n_vents)

          DEALLOCATE(x_vent_end_temp)
          DEALLOCATE(y_vent_end_temp)
                    
       END IF
       
       REWIND(input_unit)

    END IF

    IF ( crop_flag ) THEN

       ! ---------- READ crop_parameters NAMELIST -----------------------------------
       READ(input_unit, crop_parameters,IOSTAT=ios )

       IF ( ios .NE. 0 ) THEN

          WRITE(*,*) 'IOSTAT=',ios
          WRITE(*,*) 'ERROR: problem with namelist CROP_PARAMETERS'
          WRITE(*,*) 'Please check the input file'
          WRITE(*,crop_parameters)
          STOP

       ELSE

          REWIND(input_unit)

       END IF

    END IF

    ! ---------- READ flow_parameters NAMELIST -----------------------------------
    READ(input_unit, flow_parameters,IOSTAT=ios )

    IF ( ios .NE. 0 ) THEN

       WRITE(*,*) 'IOSTAT=',ios
       WRITE(*,*) 'ERROR: problem with namelist FLOW_PARAMETERS'
       WRITE(*,*) 'Please check the input file'
       WRITE(*,flow_parameters)
       STOP

    ELSE

       IF ( max_n_lobes .EQ. -9999 ) THEN

          max_n_lobes = min_n_lobes

       END IF

       ! Check if volume_flag is set
       if (volume_flag) then

          ! Fixed dimension flag logic
          if (fixed_dimension_flag ) then
             avg_lobe_thickness = total_volume / (n_flows * lobe_area * 0.5     &
                  * (min_n_lobes + max_n_lobes))
             print *, "Average Lobe thickness = ", avg_lobe_thickness, " m"

          else
             lobe_area = total_volume / (n_flows * avg_lobe_thickness * 0.5     &
                  * (min_n_lobes + max_n_lobes))
             print *, "Lobe area = ", lobe_area, " m2"

          end if

       end if

       REWIND(input_unit)

    END IF

    IF ( restart_flag) THEN

       ! ---------- READ restart_parameters NAMELIST -----------------------------------
       READ(input_unit, restart_parameters,IOSTAT=ios )

       IF ( ios .NE. 0 ) THEN

          WRITE(*,*) 'IOSTAT=',ios
          WRITE(*,*) 'ERROR: problem with namelist RESTART_PARAMETERS'
          WRITE(*,*) 'Please check the input file'
          WRITE(*,restart_parameters)
          STOP

       ELSE

          ALLOCATE(restart_files_temp(n_restarts))
          ALLOCATE(restart_filling_parameters_temp(n_restarts))

          restart_files_temp(1:n_restarts) = restart_files(1:n_restarts)
          restart_filling_parameters_temp(1:n_restarts) = restart_filling_parameters(1:n_restarts)

          DEALLOCATE(restart_files)
          DEALLOCATE(restart_filling_parameters)

          ALLOCATE(restart_files(n_restarts))
          ALLOCATE(restart_filling_parameters(n_restarts))

          restart_files(:) = restart_files_temp(:)
          restart_filling_parameters(:) = restart_filling_parameters_temp(:)

          DEALLOCATE(restart_files_temp)
          DEALLOCATE(restart_filling_parameters_temp)

          WRITE(*,*) 'restart_files ',restart_files 

          REWIND(input_unit)

       END IF

    END IF


    ! ---------- READ numerical_parameters NAMELIST -----------------------------------
    READ(input_unit, numerical_parameters,IOSTAT=ios )

    IF ( ios .NE. 0 ) THEN

       WRITE(*,*) 'IOSTAT=',ios
       WRITE(*,*) 'ERROR: problem with namelist NUMERICAL_PARAMETERS'
       WRITE(*,*) 'Please check the input file'
       WRITE(*,numerical_parameters)
       STOP

    ELSE

       nv2 = nv*nv
       inv_nv2 = 1.0_wp / nv2
       REWIND(input_unit)

    END IF

    ! ---------- READ numerical_parameters NAMELIST -----------------------------------
    IF ( union_diff_flag ) THEN

       READ(input_unit, union_diff_parameters,IOSTAT=ios )

       IF ( ios .NE. 0 ) THEN

          WRITE(*,*) 'IOSTAT=',ios
          WRITE(*,*) 'ERROR: problem with namelist UNION_DIFF_PARAMETERS'
          WRITE(*,*) 'Please check the input file'
          WRITE(*,union_diff_parameters)
          STOP

       ELSE

          INQUIRE (FILE=union_diff_file,exist=lexist)

          IF (lexist .EQV. .FALSE.) THEN

             WRITE(*,*) 'Union diff file not found'
             union_diff_flag = .FALSE.

          END IF

       END IF

    END IF

    !------ search for masking thresholds ---------------------------------------

    REWIND(input_unit)

    tend1 = .FALSE.

    WRITE(*,*) 'Searching for masking thresholds'

    n_masking = 0

    masking_search: DO

       READ(input_unit,*, END = 300 ) card

       IF( TRIM(card) == 'MASKING_THRESHOLDS' ) THEN

          EXIT masking_search

       END IF

    END DO masking_search


    READ(input_unit,*) n_masking

    WRITE(*,*) 'n_masking ',n_masking

    ALLOCATE( masking_threshold( n_masking ) )

    DO i = 1, n_masking

       READ(input_unit,*) masking_threshold(i) 

       WRITE(*,*) i , masking_threshold(i)  

    END DO

    GOTO 310
300 tend1 = .TRUE.
310 CONTINUE

    !------ end search for masking thresholds -----------------------------------

    ! Initialize loop
    i = 0
    base_name = run_name
    condition = .true.

    ! Loop to find a unique run_name
    do while (condition)

       write(run_name, '(A,"_",I3.3)') trim(base_name), i

       write(backup_file, '(A,"_inp.bak")') trim(run_name)

       ! Check if the file exists
       inquire(file=trim(backup_file), exist=condition)

       i = i + 1
    end do

    ! File copy equivalent in Fortran 90
    call execute_command_line("cp mr_lava_loba.inp "//trim(backup_file))

    ! Output the run name
    print *, 'Run name ', trim(run_name)
    print *, ''

    RETURN

  END SUBROUTINE read_param

  SUBROUTINE read_topo

    IMPLICIT NONE

    INTEGER :: i

    INTEGER :: cols, rows

    REAL(wp), allocatable :: arr_temp(:,:), xc_temp(:), yc_temp(:)
    REAL(wp), allocatable :: xc(:) , yc(:)

    REAL(wp) :: xE, xW, yS, yN

    CHARACTER*40 :: output_file
    
    CALL read_asc(source,arr_temp, lx, ly, cols, rows, cell, nd)

    allocate(xc_temp(cols))
    allocate(yc_temp(rows))    

    WRITE(*,*)

    close(topo_unit)    

    IF ( crop_flag) THEN

       ! Calculate cell centers
       do i = 1, cols
          xc_temp(i) = lx + cell * (0.5 + (i - 1))
       end do
       do i = 1, rows
          yc_temp(i) = ly + cell * (0.5 + (i - 1))
       end do

       xW = MINVAL(x_vent) - west_to_vent
       xE = MAXVAL(x_vent) + east_to_vent
       yS = MINVAL(y_vent) - south_to_vent
       yN = MAXVAL(y_vent) + north_to_vent

       WRITE(*,*) 'Cropping of original DEM'
       WRITE(*,*) 'xW,xE,yS,yN', xW, xE, yS, yN

       ! crop the DEM to the desired domain
       iW = MAX(0, (floor((xW - lx) / cell)) ) + 1
       iE = MIN(cols, (ceiling((xE - lx) / cell)) ) + 1
       jS = MAX(0, (floor((yS - ly) / cell)) ) + 1
       jN = MIN(rows, (ceiling((yN - ly) / cell)) ) + 1

       WRITE(*,*) 'iW,iE,jS,jN', iW, iE, jS, jN
       WRITE(*,*)

       nx = iE-iW+1
       ny = jN-jS+1
       allocate(Ztopo(ny, nx))
       allocate(xc(nx))
       ALLOCATE(yc(ny))

       Ztopo = arr_temp(jS:jN,iW:iE)
       xc = xc_temp(iW:iE)
       yc = yc_temp(jS:jN)

       lx = xc(1) - 0.5_wp * cell
       ly = yc(1) - 0.5_wp * cell

       WRITE(*,*) 'lx,ly ',lx,ly

       output_file = trim(run_name) // '_cropped_DEM.asc'
       CALL write_asc(Ztopo, output_file, lx, ly, cell, 0.0_wp)
                       
    ELSE

       nx = cols
       ny = rows

       allocate(Ztopo(ny, nx))
       Ztopo = arr_temp

       allocate(xc(nx))
       ALLOCATE(yc(ny))

       xc(:) = xc_temp(:)
       yc(:) = yc_temp(:)

    END IF

    xcmin = MINVAL(xc)
    xcmax = MAXVAL(xc)

    ycmin = MINVAL(yc)
    ycmax = MAXVAL(yc)

    !WRITE(*,*) 'xcmin,xcmax ',xcmin,xcmax
    !WRITE(*,*) 'ycmin,ycmax ',ycmin,ycmax

    allocate(Xtopo(ny, nx))
    allocate(Ytopo(ny, nx))

    do i = 1, ny

       Xtopo(i, 1:nx) = xc(1:nx)
       Ytopo(i, 1:nx) = yc(i)

    end do

    allocate(filling_parameter(ny,nx))

    filling_parameter(1:ny,1:nx) = 1.0_wp - thickening_parameter

    RETURN

  END SUBROUTINE read_topo


  SUBROUTINE read_restart

    IMPLICIT NONE

    INTEGER :: i_restart
    REAL(wp), ALLOCATABLE :: Zflow_old(:,:)
    REAL(wp), ALLOCATABLE :: arr_temp(:,:)

    REAL(wp) :: lx_re, ly_re, cell_re, nd_re
    INTEGER :: cols_re, rows_re

    REAL(wp) :: filling_parameter_i

    ALLOCATE(Zflow_old(ny,nx))    

    DO i_restart=1, n_restarts

       CALL read_asc(restart_files(i_restart),arr_temp, lx_re, ly_re, cols_re, rows_re, cell_re, nd_re)

       IF ( ( cols_re .EQ. cols ) .AND. ( rows_re .EQ. rows ) .AND. ( ABS(lx_re-lx) <= eps ) .AND. &
            ( ABS(ly_re-ly) <= eps ) .AND. ( ABS(cell_re-cell) <= eps ) ) THEN

          WRITE(*,*) "Check on restart size OK"

       ELSE

          WRITE(*,*) "Check on restart size FAILED"
          STOP

       END IF

       IF (crop_flag) THEN

          Zflow_old(1:ny,1:nx) = arr_temp(jS:jN,iW:iE)

       ELSE

          Zflow_old(1:ny,1:nx) = arr_temp(1:ny,1:nx)

       END IF

       ! Load the relevant filling_parameter (to account for "subsurface flows")
       filling_parameter_i = restart_filling_parameters(i_restart)

       Ztopo = Ztopo + Zflow_old * filling_parameter_i

       CLOSE(restart_unit)  

    END DO

    DEALLOCATE( Zflow_old )
    DEALLOCATE( arr_temp )

    RETURN

  END SUBROUTINE read_restart

  SUBROUTINE write_masking

    USE flow, ONLY : Zflow, Zflow_mask, Zud

    IMPLICIT NONE

    INTEGER :: i_thr, i
    INTEGER :: max_lobes

    REAL(wp) :: total_Zflow, total_masked_Zflow
    REAL(wp) :: threshold
    REAL(wp) :: volume_fraction
    CHARACTER(LEN=40) :: masked_file, masking_str1, masking_str2
    REAL(wp) :: fitting_parameter

    max_lobes = floor(MAXVAL(Zflow)/avg_lobe_thickness)

    ! Sum the values in Zflow
    total_Zflow = sum(Zflow)

    DO i_thr = 1,n_masking

       DO i = 1,10*max_lobes

          threshold = i * 0.1_wp * avg_lobe_thickness

          Zflow_mask = Zflow * merge(1.0_wp,0.0_wp,Zflow.GT.threshold)
          total_masked_Zflow = sum(Zflow_mask)

          volume_fraction = total_masked_Zflow / total_Zflow

          IF (volume_fraction < masking_threshold(i_thr)) THEN

             WRITE(*,*)
             WRITE(*,*) 'Masking threshold', masking_threshold(i_thr)
             WRITE(*,*) 'Total volume (m3) =', cell**2 * total_Zflow,                  &
                  'Masked volume (m3) =', cell**2 * total_masked_Zflow,            &
                  'Volume fraction =', volume_fraction

             !WRITE(*,*) 'Total area', cell**2 * sum(merge(0,1,Zflow > 0)),      &
             !     ' m2 Masked area',cell**2 * sum(merge(0,1,masked_Zflow > 0)), &
             !     ' m2'

             !WRITE(*,*) 'Average thickness full',                               &
             !     total_Zflow / sum(merge(0,1,Zflow > 0)),                      &
             !     ' m Average thickness mask', sum(masked_Zflow) /              &
             !     sum(merge(0,1,masked_Zflow > 0)), ' m'

             ! Convert the masking_threshold value to a string and replace '.' with '_'
             write(masking_str1, '(F6.2)') masking_threshold(i_thr)
             masking_str1 = adjustl(masking_str1)
             call replace_dot(masking_str1, masking_str2)

             IF ( nc_flag ) THEN

                ! Concatenate the strings
                masked_file = trim(run_name) // '_thickness_masked_' // trim(masking_str2) // '.nc'

                CALL write_netcdf_2d(Zflow_mask,  masked_file, lx, ly, cell, 0.0_wp, 'm', 33 )

             END IF

             IF ( asc_flag ) THEN

                ! Concatenate the strings
                masked_file = trim(run_name) // '_thickness_masked_' // trim(masking_str2) // '.asc'

                CALL write_asc(Zflow_mask, masked_file, lx, ly, cell, 0.0_wp)

             END IF

             EXIT

          END IF
          
       END DO

       IF (union_diff_flag) THEN
          
          fitting_parameter = REAL(count( MIN(Zud, Zflow_mask) > 0 )) /    &
               REAL(count( MAX(Zud, Zflow_mask) > 0 ))
          
          WRITE(*,*) '--------------------------------'
          WRITE(*,*) 'With masking threshold', masking_threshold(i_thr)
          WRITE(*,*) 'Union area', count( MIN(Zud, Zflow_mask) > 0 ) * cell**2
          WRITE(*,*) 'Intersection area', count( MAX(Zud, Zflow_mask) > 0 ) * cell**2
          WRITE(*,*) 'Fitting parameter', fitting_parameter
          
       END IF
              
    END DO

    RETURN

  END SUBROUTINE write_masking

  SUBROUTINE init_union_diff

    USE flow, ONLY : Zflow, Zud

    IMPLICIT NONE

    REAL(wp) :: lx_ud, ly_ud
    INTEGER :: cols_ud, rows_ud
    REAL(wp) :: cell_ud
    REAL(wp) :: nd_ud
    REAL(wp), ALLOCATABLE :: xin_1D(:), yin_1D(:), Zs_ud(:,:), Zout_2D(:,:)

    INTEGER :: i, max_lobes

    max_lobes = floor(MAXVAL(Zflow)/avg_lobe_thickness)

    CALL read_asc(union_diff_file,Zs_ud, lx_ud, ly_ud, cols_ud, rows_ud, cell_ud, nd_ud)

    ! WRITE(*,*) lx_ud, ly_ud, cols_ud, rows_ud, cell_ud
    ! WRITE(*,*) lx, ly, size(Zflow,2), size(Zflow,1), cell

    IF ( ( cols_ud .NE. size(Zflow,2)) .OR. (rows_ud .NE. size(Zflow,1)) .OR.&
         ( ABS(lx_ud-lx)>=eps ) .OR. ( ABS(ly_ud-ly)>=eps ) .OR. ( ABS(cell_ud-cell)>=eps ) ) THEN

       WRITE(*,*) "Union_diff_file", union_diff_file
       WRITE(*,*) "Different header: interpolating data"

       ALLOCATE( xin_1D(cols_ud) , yin_1D(rows_ud) )

       ! Calculate cell centers
       do i = 1, cols_ud
          xin_1D(i) = lx_ud + cell_ud * (0.5 + (i - 1))
       end do
       do i = 1, rows_ud
          yin_1D(i) = ly_ud + cell_ud * (0.5 + (i - 1))
       end do

       CALL interp2Dgrids(xin_1D, yin_1D, Zs_ud, Xtopo, Ytopo, Zout_2D)

       DEALLOCATE( xin_1D , yin_1D )
       DEALLOCATE( Zs_ud )
       Zud = Zout_2D
       DEALLOCATE( Zout_2D )       

    ELSE

       Zud = Zs_ud 

    END IF

    RETURN

  END SUBROUTINE init_union_diff

    
  SUBROUTINE read_asc(asc_file,asc_array, x0, y0, cols, rows, cell_size, nodata)

    IMPLICIT NONE

    CHARACTER*40, INTENT(IN) :: asc_file
    REAL(wp), ALLOCATABLE, INTENT(OUT) :: asc_array(:,:)
    REAL(wp), INTENT(OUT) :: x0, y0
    INTEGER, INTENT(OUT) :: cols, rows
    REAL(wp), INTENT(OUT) :: cell_size
    REAL(wp), INTENT(OUT) :: nodata

    LOGICAL :: lexist
    INTEGER :: i
    REAL(wp), ALLOCATABLE :: buffer(:,:)
    CHARACTER(LEN=15) :: chara


    INQUIRE(FILE=asc_file,EXIST=lexist)

    IF (lexist) THEN

       OPEN(asc_unit, file=asc_file, status='old', action='read')

    ELSE

       WRITE(*,*) 'no ascii file: ',TRIM(asc_file)
       STOP

    ENDIF

    READ(asc_unit,*) chara, cols
    READ(asc_unit,*) chara, rows
    READ(asc_unit,*) chara, x0
    READ(asc_unit,*) chara, y0
    READ(asc_unit,*) chara, cell_size
    READ(asc_unit,*) chara, nodata

    ! Allocate the arrays based on dimensions
    allocate(buffer(cols, rows))
    allocate(asc_array(rows, cols))

    WRITE(*,*)
    WRITE(*,*) 'Reading DEM file:',TRIM(asc_file)

    read(asc_unit, *) buffer

    ! Flip the buffer vertically into the data array
    do i = 1, rows
       asc_array(i, :) = buffer(:,rows - i + 1)  ! Flip by copying rows in reverse order
    end do

    deallocate(buffer)
    close(asc_unit)

    RETURN

  END SUBROUTINE read_asc

  SUBROUTINE write_asc(out_array, output_file, x0, y0, cell_size, nodata)

    IMPLICIT NONE

    REAL(wp), INTENT(IN) :: out_array(:,:)
    CHARACTER*40, INTENT(IN) :: output_file
    REAL(wp), INTENT(IN) :: x0, y0
    REAL(wp), INTENT(IN) :: cell_size
    REAL(wp), INTENT(IN) :: nodata

    INTEGER :: out_cells_x, out_cells_y
    INTEGER :: j

    WRITE(*,*) "Saving asc file: ", TRIM(output_file)
    
    OPEN(output_unit,FILE=TRIM(output_file),status='unknown',form='formatted')

    out_cells_y = size(out_array, 1)
    out_cells_x = size(out_array, 2)

    WRITE(output_unit,'(A,I5)') 'ncols ', out_cells_x
    WRITE(output_unit,'(A,I5)') 'nrows ', out_cells_y
    WRITE(output_unit,'(A,F15.3)') 'xllcorner ', x0
    WRITE(output_unit,'(A,F15.3)') 'yllcorner ', y0
    WRITE(output_unit,'(A,F15.3)') 'cellsize ', cell_size
    WRITE(output_unit,'(A,F15.3)') 'NODATA_value ', nodata

    
    DO j = out_cells_y,1,-1

       WRITE(output_unit,'(2000ES12.3E3)') out_array(j,1:out_cells_x)

    ENDDO

    CLOSE(output_unit)

    WRITE(*,*) "Saving completed"

  END SUBROUTINE write_asc

  subroutine replace_dot(in_str, out_str)
    character(len=*), intent(in) :: in_str
    character(len=*), intent(out) :: out_str
    integer :: i
    out_str = in_str
    do i = 1, len_trim(in_str)
       if (out_str(i:i) == '.') out_str(i:i) = '_'
    end do
  end subroutine replace_dot

  subroutine write_netcdf_2d(out_array, output_file, x0, y0, cell_size, nodata_value, units, utm_zone)

    use netcdf
    implicit none

    ! Arguments
    REAL(wp), intent(in) :: out_array(ny,nx)           ! 2D array of data
    CHARACTER*40, INTENT(IN) :: output_file
    REAL(wp), INTENT(IN) :: x0, y0
    REAL(wp), INTENT(IN) :: cell_size
    REAL(wp), intent(in) :: nodata_value        ! NoData (missing) value for the data array
    character(len=*), intent(in) :: units      ! Units of the data (e.g., 'meters', 'temperature')
    INTEGER, intent(in) :: utm_zone            ! UTM zone (e.g., 33, 34)

    ! integer :: nx, ny              ! Dimensions of the data array
    REAL(wp) :: x_coords(nx)         ! 1D array of x-coordinates (UTM Easting)
    REAL(wp) :: y_coords(ny)         ! 1D array of y-coordinates (UTM Northing)

    ! Local variables
    integer :: ncid, x_dimid, y_dimid, varid_data, varid_x, varid_y, retval, crs_varid, varid
    integer :: data_dimids(2)

    ! character(len=100) :: crs                  ! Projection string
    character(len=16) :: crs_name

    INTEGER :: i

    ! Calculate cell centers
    do i = 1, nx
       x_coords(i) = x0 + cell_size * (0.5 + (i - 1))
    end do

    do i = 1, ny
       y_coords(i) = y0 + cell_size * (0.5 + (i - 1))
    end do
    
    ! Create a new NetCDF file (NetCDF4 format with HDF5 support)
    retval = nf90_create(TRIM(output_file), nf90_netcdf4, ncid)
    if (retval /= nf90_noerr) stop 'Error creating NetCDF file.'

    ! Define dimensions for x and y
    retval = nf90_def_dim(ncid, 'x', nx, x_dimid)
    if (retval /= nf90_noerr) stop 'Error defining x dimension.'
    retval = nf90_def_dim(ncid, 'y', ny, y_dimid)
    if (retval /= nf90_noerr) stop 'Error defining y dimension.'

    ! Define the x and y coordinate variables
    retval = nf90_def_var(ncid, 'x', nf90_double, [x_dimid], varid_x)
    if (retval /= nf90_noerr) stop 'Error defining x variable.'
    retval = nf90_def_var(ncid, 'y', nf90_double, [y_dimid], varid_y)
    if (retval /= nf90_noerr) stop 'Error defining y variable.'

    ! Define the 2D data variable
    data_dimids = (/x_dimid, y_dimid/)
    retval = nf90_def_var(ncid, 'data', nf90_double, data_dimids, varid_data)
    if (retval /= nf90_noerr) stop 'Error defining data variable.'

    ! Enable compression (level 4 as an example, ranges from 0 to 9)
    retval = nf90_def_var_deflate(ncid, varid_data, shuffle=1, deflate=1, deflate_level=4)

    ! Add metadata: units for the data and UTM zone
    retval = nf90_put_att(ncid, varid_x, 'units', trim(units))
    if (retval /= nf90_noerr) stop 'Error adding units attribute.'

    retval = nf90_put_att(ncid, varid_x, 'long_name', 'Easting')
    if (retval /= nf90_noerr) stop 'Error adding long_name attribute.'

    retval = nf90_put_att(ncid, varid_x, 'standard_name', 'projection_x_coordinate')
    if (retval /= nf90_noerr) stop 'Error adding standard_name attribute.'

    retval = nf90_put_att(ncid, varid_y, 'units', trim(units))
    if (retval /= nf90_noerr) stop 'Error adding units attribute.'

    retval = nf90_put_att(ncid, varid_y, 'long_name', 'Northing')
    if (retval /= nf90_noerr) stop 'Error adding long_name attribute.'

    retval = nf90_put_att(ncid, varid_y, 'standard_name', 'projection_y_coordinate')
    if (retval /= nf90_noerr) stop 'Error adding standard_name attribute.'

    retval = nf90_put_att(ncid, varid_data, 'units', trim(units))
    if (retval /= nf90_noerr) stop 'Error adding units attribute.'


    ! Add the _FillValue attribute for NoData value
    retval = nf90_put_att(ncid, varid_data, '_FillValue', nodata_value)
    if (retval /= nf90_noerr) stop 'Error adding _FillValue (NoData value) attribute.'

    ! Define the CRS (UTM) as a scalar variable (no dimensions needed)
    write(crs_name, '(I0)') utm_zone
    crs_name = 'UTM_' // trim(crs_name)
    retval = nf90_def_var(ncid, 'crs', nf90_char, crs_varid)

    ! Add CF-compliant attributes to define the UTM CRS
    retval = nf90_put_att(ncid, crs_varid, 'grid_mapping_name', 'transverse_mercator')
    retval = nf90_put_att(ncid, crs_varid, 'utm_zone_number', utm_zone)
    retval = nf90_put_att(ncid, crs_varid, 'false_easting', 500000.0d0)
    retval = nf90_put_att(ncid, crs_varid, 'false_northing', 0.0d0)
    retval = nf90_put_att(ncid, crs_varid, 'scale_factor_at_central_meridian', 0.9996d0)
    retval = nf90_put_att(ncid, crs_varid, 'longitude_of_central_meridian', &
         real(6 * utm_zone - 183, kind=8))
    retval = nf90_put_att(ncid, crs_varid, 'latitude_of_projection_origin', 0.0d0)
    retval = nf90_put_att(ncid, crs_varid, 'semi_major_axis', 6378137.0d0)
    retval = nf90_put_att(ncid, crs_varid, 'inverse_flattening', 298.257223563d0)

    ! Add the EPSG code and WKT spatial reference attribute
    retval = nf90_put_att(ncid, crs_varid, 'EPSG_code', 'EPSG:32633')  ! Replace XX with your UTM zone

    ! Link the data variable to the CRS variable through 'grid_mapping'
    retval = nf90_put_att(ncid, varid, 'grid_mapping', 'crs')

    ! End define mode
    retval = nf90_enddef(ncid)
    if (retval /= nf90_noerr) stop 'Error ending define mode in NetCDF file.'

    ! Write the x and y coordinate variables
    retval = nf90_put_var(ncid, varid_x, x_coords)
    if (retval /= nf90_noerr) stop 'Error writing x-coordinates.'
    retval = nf90_put_var(ncid, varid_y, y_coords)
    if (retval /= nf90_noerr) stop 'Error writing y-coordinates.'

    ! Write the 2D data array
    retval = nf90_put_var(ncid, varid_data, TRANSPOSE(out_array) )
    if (retval /= nf90_noerr) stop 'Error writing 2D data array.'

    ! Close the NetCDF file
    retval = nf90_close(ncid)
    if (retval /= nf90_noerr) stop 'Error closing NetCDF file.'

    WRITE(*,*) "NetCDF file created successfully: ", TRIM(output_file)

    RETURN

  end subroutine write_netcdf_2d


  subroutine interp2Dgrids(xin_1D, yin_1D, Zin_2D, Xout_2D, Yout_2D, Zout_2D)
    implicit none

    ! Input parameters
    real(wp), intent(in) :: xin_1D(:), yin_1D(:)  ! Original grid (1D)
    real(wp), intent(in) :: Zin_2D(:,:)           ! Original grid Z values (2D)
    real(wp), intent(in) :: Xout_2D(:,:), Yout_2D(:,:)  ! New grid (2D)

    ! Output parameter
    real(wp), ALLOCATABLE, intent(out) :: Zout_2D(:,:)  ! Interpolated output (2D)

    ! Local variables
    integer :: nx_in, ny_in             ! Size of original grid
    integer :: nx_out, ny_out           ! Size of new grid

    real(wp) :: xinMin, yinMin, cellin
    real(wp), ALLOCATABLE :: xi(:), yi(:)
    real(wp), ALLOCATABLE :: xi_fract(:), yi_fract(:)
    real(wp), ALLOCATABLE :: xi_out_yi(:, :)
    integer, ALLOCATABLE :: ix(:), iy(:), ix1(:), iy1(:)
    integer :: i, j

    nx_in = size(xin_1D)
    ny_in = size(yin_1D)

    nx_out = size(Xout_2D,2)
    ny_out = size(Xout_2D,1)
    
    ALLOCATE(Zout_2D(ny_out,nx_out))
    ALLOCATE(xi(ny_out),yi(nx_out))
    ALLOCATE(xi_fract(ny_out),yi_fract(nx_out))
    ALLOCATE( xi_out_yi(ny_out, nx_out) )
    ALLOCATE ( ix(nx_out), iy(ny_out), ix1(nx_out), iy1(ny_out) )
    
    ! Compute minimum values and cell size for the original grid
    xinMin = minval(xin_1D)
    yinMin = minval(yin_1D)
    cellin = xin_1D(2) - xin_1D(1)

    ! Calculate the positions of the target points in terms of the original grid
    xi = (Xout_2D(1, :) - xinMin) / cellin
    yi = (Yout_2D(:, 1) - yinMin) / cellin

    ! Compute ix and iy, ensuring indices are within bounds
    do i = 1, nx_out
       ix(i) = max(1, min(nx_in-1, ceiling(xi(i))))
       ix1(i) = ix(i) + 1
    end do

    do j = 1, ny_out
       iy(j) = max(1, min(ny_in-1, ceiling(yi(j))))
       iy1(j) = iy(j) + 1
    end do

    ! Compute fractional coordinates within each cell
    xi_fract = max(0.0_wp, min(1.0_wp, xi - real(ix) + 1.0_wp))
    yi_fract = max(0.0_wp, min(1.0_wp, yi - real(iy) + 1.0_wp))

    ! Compute the bilinear interpolation factors
    do j = 1, ny_out
       do i = 1, nx_out
          xi_out_yi(j, i) = yi_fract(j) * xi_fract(i)
       end do
    end do

    ! Perform bilinear interpolation
    do j = 1, ny_out
       do i = 1, nx_out
          Zout_2D(j, i) = xi_out_yi(j, i) * Zin_2D(iy1(j), ix1(i)) + &
               (xi_fract(i) - xi_out_yi(j, i)) * Zin_2D(iy(j), ix1(i)) + &
               (yi_fract(j) - xi_out_yi(j, i)) * Zin_2D(iy1(j), ix(i)) + &
               (1.0_wp - xi_fract(i) - yi_fract(j) + xi_out_yi(j, i)) * Zin_2D(iy(j), ix(i))
       end do
    end do

  end subroutine interp2Dgrids


END MODULE inpout
